/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetPageChanges200Response,
  VerifyContent200Response,
  VerifyContentRequest,
} from '../models/index';
import {
    GetPageChanges200ResponseFromJSON,
    GetPageChanges200ResponseToJSON,
    VerifyContent200ResponseFromJSON,
    VerifyContent200ResponseToJSON,
    VerifyContentRequestFromJSON,
    VerifyContentRequestToJSON,
} from '../models/index';

export interface GetPageChangesRequest {
    projectId: string;
    status?: GetPageChangesStatusEnum;
    pageId?: string;
    limit?: number;
}

export interface VerifyContentOperationRequest {
    projectId: string;
    verifyContentRequest: VerifyContentRequest;
}

/**
 * 
 */
export class ContentVerificationApi extends runtime.BaseAPI {

    /**
     * Get change history for pages in a project
     * Get page changes
     */
    async getPageChangesRaw(requestParameters: GetPageChangesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPageChanges200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getPageChanges().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['pageId'] != null) {
            queryParameters['pageId'] = requestParameters['pageId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/projects/{projectId}/changes`;
        urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPageChanges200ResponseFromJSON(jsonValue));
    }

    /**
     * Get change history for pages in a project
     * Get page changes
     */
    async getPageChanges(requestParameters: GetPageChangesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPageChanges200Response> {
        const response = await this.getPageChangesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Check if page content has changed since last crawl
     * Verify page content
     */
    async verifyContentRaw(requestParameters: VerifyContentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerifyContent200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling verifyContent().'
            );
        }

        if (requestParameters['verifyContentRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyContentRequest',
                'Required parameter "verifyContentRequest" was null or undefined when calling verifyContent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/projects/{projectId}/verify-content`;
        urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyContentRequestToJSON(requestParameters['verifyContentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerifyContent200ResponseFromJSON(jsonValue));
    }

    /**
     * Check if page content has changed since last crawl
     * Verify page content
     */
    async verifyContent(requestParameters: VerifyContentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerifyContent200Response> {
        const response = await this.verifyContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetPageChangesStatusEnum = {
    New: 'new',
    Same: 'same',
    Changed: 'changed',
    Removed: 'removed'
} as const;
export type GetPageChangesStatusEnum = typeof GetPageChangesStatusEnum[keyof typeof GetPageChangesStatusEnum];
