/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeleteSuggestion200Response,
  GenerateSuggestions200Response,
  GenerateSuggestionsRequest,
  Suggestion,
  UpdateSuggestionRequest,
} from '../models/index';
import {
    DeleteSuggestion200ResponseFromJSON,
    DeleteSuggestion200ResponseToJSON,
    GenerateSuggestions200ResponseFromJSON,
    GenerateSuggestions200ResponseToJSON,
    GenerateSuggestionsRequestFromJSON,
    GenerateSuggestionsRequestToJSON,
    SuggestionFromJSON,
    SuggestionToJSON,
    UpdateSuggestionRequestFromJSON,
    UpdateSuggestionRequestToJSON,
} from '../models/index';

export interface DeleteSuggestionRequest {
    projectId: string;
    suggestionId: string;
}

export interface GenerateSuggestionsOperationRequest {
    projectId: string;
    generateSuggestionsRequest?: GenerateSuggestionsRequest;
}

export interface GetSuggestionsRequest {
    projectId: string;
    status?: GetSuggestionsStatusEnum;
}

export interface UpdateSuggestionOperationRequest {
    projectId: string;
    suggestionId: string;
    updateSuggestionRequest: UpdateSuggestionRequest;
}

/**
 * 
 */
export class SuggestionsApi extends runtime.BaseAPI {

    /**
     * Delete a link suggestion
     * Delete suggestion
     */
    async deleteSuggestionRaw(requestParameters: DeleteSuggestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteSuggestion200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling deleteSuggestion().'
            );
        }

        if (requestParameters['suggestionId'] == null) {
            throw new runtime.RequiredError(
                'suggestionId',
                'Required parameter "suggestionId" was null or undefined when calling deleteSuggestion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/projects/{projectId}/suggestions/{suggestionId}`;
        urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"suggestionId"}}`, encodeURIComponent(String(requestParameters['suggestionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteSuggestion200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete a link suggestion
     * Delete suggestion
     */
    async deleteSuggestion(requestParameters: DeleteSuggestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteSuggestion200Response> {
        const response = await this.deleteSuggestionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate new AI-powered link suggestions for a project
     * Generate link suggestions
     */
    async generateSuggestionsRaw(requestParameters: GenerateSuggestionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenerateSuggestions200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling generateSuggestions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/projects/{projectId}/suggestions`;
        urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateSuggestionsRequestToJSON(requestParameters['generateSuggestionsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenerateSuggestions200ResponseFromJSON(jsonValue));
    }

    /**
     * Generate new AI-powered link suggestions for a project
     * Generate link suggestions
     */
    async generateSuggestions(requestParameters: GenerateSuggestionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenerateSuggestions200Response> {
        const response = await this.generateSuggestionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get AI-generated link suggestions for a project
     * Get link suggestions
     */
    async getSuggestionsRaw(requestParameters: GetSuggestionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Suggestion>>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getSuggestions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/projects/{projectId}/suggestions`;
        urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SuggestionFromJSON));
    }

    /**
     * Get AI-generated link suggestions for a project
     * Get link suggestions
     */
    async getSuggestions(requestParameters: GetSuggestionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Suggestion>> {
        const response = await this.getSuggestionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update the status of a link suggestion
     * Update suggestion status
     */
    async updateSuggestionRaw(requestParameters: UpdateSuggestionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Suggestion>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling updateSuggestion().'
            );
        }

        if (requestParameters['suggestionId'] == null) {
            throw new runtime.RequiredError(
                'suggestionId',
                'Required parameter "suggestionId" was null or undefined when calling updateSuggestion().'
            );
        }

        if (requestParameters['updateSuggestionRequest'] == null) {
            throw new runtime.RequiredError(
                'updateSuggestionRequest',
                'Required parameter "updateSuggestionRequest" was null or undefined when calling updateSuggestion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/projects/{projectId}/suggestions/{suggestionId}`;
        urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"suggestionId"}}`, encodeURIComponent(String(requestParameters['suggestionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSuggestionRequestToJSON(requestParameters['updateSuggestionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuggestionFromJSON(jsonValue));
    }

    /**
     * Update the status of a link suggestion
     * Update suggestion status
     */
    async updateSuggestion(requestParameters: UpdateSuggestionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Suggestion> {
        const response = await this.updateSuggestionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetSuggestionsStatusEnum = {
    Pending: 'pending',
    Approved: 'approved',
    Rejected: 'rejected',
    Implemented: 'implemented'
} as const;
export type GetSuggestionsStatusEnum = typeof GetSuggestionsStatusEnum[keyof typeof GetSuggestionsStatusEnum];
