/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  VerifyContent200Response,
  VerifyContentRequest,
} from '../models/index';
import {
    VerifyContent200ResponseFromJSON,
    VerifyContent200ResponseToJSON,
    VerifyContentRequestFromJSON,
    VerifyContentRequestToJSON,
} from '../models/index';

export interface VerifyContentOperationRequest {
    projectId: string;
    verifyContentRequest: VerifyContentRequest;
}

/**
 * 
 */
export class ContentVerificationApi extends runtime.BaseAPI {

    /**
     * Check if page content has changed since last crawl
     * Verify page content
     */
    async verifyContentRaw(requestParameters: VerifyContentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerifyContent200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling verifyContent().'
            );
        }

        if (requestParameters['verifyContentRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyContentRequest',
                'Required parameter "verifyContentRequest" was null or undefined when calling verifyContent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/projects/{projectId}/verify-content`;
        urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyContentRequestToJSON(requestParameters['verifyContentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerifyContent200ResponseFromJSON(jsonValue));
    }

    /**
     * Check if page content has changed since last crawl
     * Verify page content
     */
    async verifyContent(requestParameters: VerifyContentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerifyContent200Response> {
        const response = await this.verifyContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
