/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddCredits200Response,
  AddCreditsRequest,
  CreditBalance,
} from '../models/index';
import {
    AddCredits200ResponseFromJSON,
    AddCredits200ResponseToJSON,
    AddCreditsRequestFromJSON,
    AddCreditsRequestToJSON,
    CreditBalanceFromJSON,
    CreditBalanceToJSON,
} from '../models/index';

export interface AddCreditsOperationRequest {
    projectId: string;
    addCreditsRequest: AddCreditsRequest;
}

export interface GetCreditsRequest {
    projectId: string;
    includeHistory?: boolean;
    startDate?: Date;
    endDate?: Date;
}

/**
 * 
 */
export class CreditsApi extends runtime.BaseAPI {

    /**
     * Add credits to a project (admin or payment webhook use)
     * Add credits
     */
    async addCreditsRaw(requestParameters: AddCreditsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddCredits200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling addCredits().'
            );
        }

        if (requestParameters['addCreditsRequest'] == null) {
            throw new runtime.RequiredError(
                'addCreditsRequest',
                'Required parameter "addCreditsRequest" was null or undefined when calling addCredits().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/projects/{projectId}/credits`;
        urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddCreditsRequestToJSON(requestParameters['addCreditsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddCredits200ResponseFromJSON(jsonValue));
    }

    /**
     * Add credits to a project (admin or payment webhook use)
     * Add credits
     */
    async addCredits(requestParameters: AddCreditsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddCredits200Response> {
        const response = await this.addCreditsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get credit balance and usage history for a project
     * Get credit balance
     */
    async getCreditsRaw(requestParameters: GetCreditsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreditBalance>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getCredits().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeHistory'] != null) {
            queryParameters['includeHistory'] = requestParameters['includeHistory'];
        }

        if (requestParameters['startDate'] != null) {
            queryParameters['startDate'] = (requestParameters['startDate'] as any).toISOString();
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['endDate'] = (requestParameters['endDate'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/projects/{projectId}/credits`;
        urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreditBalanceFromJSON(jsonValue));
    }

    /**
     * Get credit balance and usage history for a project
     * Get credit balance
     */
    async getCredits(requestParameters: GetCreditsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreditBalance> {
        const response = await this.getCreditsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
