/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetImplementation200Response,
  ImplementationRequest,
  ImplementationResponse,
  ListImplementations200Response,
  RollbackImplementation200Response,
  RollbackImplementationRequest,
} from '../models/index';
import {
    GetImplementation200ResponseFromJSON,
    GetImplementation200ResponseToJSON,
    ImplementationRequestFromJSON,
    ImplementationRequestToJSON,
    ImplementationResponseFromJSON,
    ImplementationResponseToJSON,
    ListImplementations200ResponseFromJSON,
    ListImplementations200ResponseToJSON,
    RollbackImplementation200ResponseFromJSON,
    RollbackImplementation200ResponseToJSON,
    RollbackImplementationRequestFromJSON,
    RollbackImplementationRequestToJSON,
} from '../models/index';

export interface GetImplementationRequest {
    projectId: string;
    implementationId: string;
}

export interface ImplementLinksRequest {
    projectId: string;
    implementationRequest: ImplementationRequest;
}

export interface ListImplementationsRequest {
    projectId: string;
    status?: ListImplementationsStatusEnum;
    platform?: ListImplementationsPlatformEnum;
    limit?: number;
    offset?: number;
}

export interface RollbackImplementationOperationRequest {
    projectId: string;
    implementationId: string;
    rollbackImplementationRequest: RollbackImplementationRequest;
}

/**
 * 
 */
export class ImplementationsApi extends runtime.BaseAPI {

    /**
     * Get detailed information about a specific implementation
     * Get implementation details
     */
    async getImplementationRaw(requestParameters: GetImplementationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetImplementation200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getImplementation().'
            );
        }

        if (requestParameters['implementationId'] == null) {
            throw new runtime.RequiredError(
                'implementationId',
                'Required parameter "implementationId" was null or undefined when calling getImplementation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/projects/{projectId}/implementations/{implementationId}`;
        urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"implementationId"}}`, encodeURIComponent(String(requestParameters['implementationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetImplementation200ResponseFromJSON(jsonValue));
    }

    /**
     * Get detailed information about a specific implementation
     * Get implementation details
     */
    async getImplementation(requestParameters: GetImplementationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetImplementation200Response> {
        const response = await this.getImplementationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Implement one or more link suggestions
     * Implement link suggestions
     */
    async implementLinksRaw(requestParameters: ImplementLinksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImplementationResponse>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling implementLinks().'
            );
        }

        if (requestParameters['implementationRequest'] == null) {
            throw new runtime.RequiredError(
                'implementationRequest',
                'Required parameter "implementationRequest" was null or undefined when calling implementLinks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/projects/{projectId}/implementations`;
        urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImplementationRequestToJSON(requestParameters['implementationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImplementationResponseFromJSON(jsonValue));
    }

    /**
     * Implement one or more link suggestions
     * Implement link suggestions
     */
    async implementLinks(requestParameters: ImplementLinksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImplementationResponse> {
        const response = await this.implementLinksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get implementation history for a project
     * List implementations
     */
    async listImplementationsRaw(requestParameters: ListImplementationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListImplementations200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listImplementations().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['platform'] != null) {
            queryParameters['platform'] = requestParameters['platform'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/projects/{projectId}/implementations`;
        urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListImplementations200ResponseFromJSON(jsonValue));
    }

    /**
     * Get implementation history for a project
     * List implementations
     */
    async listImplementations(requestParameters: ListImplementationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListImplementations200Response> {
        const response = await this.listImplementationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Undo a link implementation and restore original content
     * Rollback implementation
     */
    async rollbackImplementationRaw(requestParameters: RollbackImplementationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RollbackImplementation200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling rollbackImplementation().'
            );
        }

        if (requestParameters['implementationId'] == null) {
            throw new runtime.RequiredError(
                'implementationId',
                'Required parameter "implementationId" was null or undefined when calling rollbackImplementation().'
            );
        }

        if (requestParameters['rollbackImplementationRequest'] == null) {
            throw new runtime.RequiredError(
                'rollbackImplementationRequest',
                'Required parameter "rollbackImplementationRequest" was null or undefined when calling rollbackImplementation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/projects/{projectId}/implementations/{implementationId}/rollback`;
        urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"implementationId"}}`, encodeURIComponent(String(requestParameters['implementationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RollbackImplementationRequestToJSON(requestParameters['rollbackImplementationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RollbackImplementation200ResponseFromJSON(jsonValue));
    }

    /**
     * Undo a link implementation and restore original content
     * Rollback implementation
     */
    async rollbackImplementation(requestParameters: RollbackImplementationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RollbackImplementation200Response> {
        const response = await this.rollbackImplementationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListImplementationsStatusEnum = {
    Pending: 'pending',
    InProgress: 'in_progress',
    Success: 'success',
    Failed: 'failed',
    RolledBack: 'rolled_back'
} as const;
export type ListImplementationsStatusEnum = typeof ListImplementationsStatusEnum[keyof typeof ListImplementationsStatusEnum];
/**
 * @export
 */
export const ListImplementationsPlatformEnum = {
    Custom: 'custom'
} as const;
export type ListImplementationsPlatformEnum = typeof ListImplementationsPlatformEnum[keyof typeof ListImplementationsPlatformEnum];
