/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BatchSyncPages200Response,
  BatchSyncPagesRequest,
  ListPages200Response,
} from '../models/index';
import {
    BatchSyncPages200ResponseFromJSON,
    BatchSyncPages200ResponseToJSON,
    BatchSyncPagesRequestFromJSON,
    BatchSyncPagesRequestToJSON,
    ListPages200ResponseFromJSON,
    ListPages200ResponseToJSON,
} from '../models/index';

export interface BatchSyncPagesOperationRequest {
    projectId: string;
    batchSyncPagesRequest: BatchSyncPagesRequest;
}

export interface ListPagesRequest {
    projectId: string;
    limit?: number;
    offset?: number;
}

/**
 * 
 */
export class PagesApi extends runtime.BaseAPI {

    /**
     * Sync multiple pages to a project (used by WordPress and other integrations)
     * Batch sync pages
     */
    async batchSyncPagesRaw(requestParameters: BatchSyncPagesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchSyncPages200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling batchSyncPages().'
            );
        }

        if (requestParameters['batchSyncPagesRequest'] == null) {
            throw new runtime.RequiredError(
                'batchSyncPagesRequest',
                'Required parameter "batchSyncPagesRequest" was null or undefined when calling batchSyncPages().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/projects/{projectId}/pages/batch`;
        urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BatchSyncPagesRequestToJSON(requestParameters['batchSyncPagesRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchSyncPages200ResponseFromJSON(jsonValue));
    }

    /**
     * Sync multiple pages to a project (used by WordPress and other integrations)
     * Batch sync pages
     */
    async batchSyncPages(requestParameters: BatchSyncPagesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchSyncPages200Response> {
        const response = await this.batchSyncPagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a list of pages for a project
     * List pages
     */
    async listPagesRaw(requestParameters: ListPagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPages200Response>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listPages().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/projects/{projectId}/pages`;
        urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListPages200ResponseFromJSON(jsonValue));
    }

    /**
     * Get a list of pages for a project
     * List pages
     */
    async listPages(requestParameters: ListPagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPages200Response> {
        const response = await this.listPagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
