/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ImplementationInstructions,
  ReportImplementationStatus200Response,
  ReportImplementationStatusRequest,
} from '../models/index';
import {
    ImplementationInstructionsFromJSON,
    ImplementationInstructionsToJSON,
    ReportImplementationStatus200ResponseFromJSON,
    ReportImplementationStatus200ResponseToJSON,
    ReportImplementationStatusRequestFromJSON,
    ReportImplementationStatusRequestToJSON,
} from '../models/index';

export interface GetImplementationInstructionsRequest {
    suggestionId: string;
}

export interface ReportImplementationStatusOperationRequest {
    reportImplementationStatusRequest: ReportImplementationStatusRequest;
}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * Get step-by-step instructions for implementing a link
     * Get implementation instructions
     */
    async getImplementationInstructionsRaw(requestParameters: GetImplementationInstructionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImplementationInstructions>> {
        if (requestParameters['suggestionId'] == null) {
            throw new runtime.RequiredError(
                'suggestionId',
                'Required parameter "suggestionId" was null or undefined when calling getImplementationInstructions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['suggestionId'] != null) {
            queryParameters['suggestionId'] = requestParameters['suggestionId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/webhook/implement-link`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImplementationInstructionsFromJSON(jsonValue));
    }

    /**
     * Get step-by-step instructions for implementing a link
     * Get implementation instructions
     */
    async getImplementationInstructions(requestParameters: GetImplementationInstructionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImplementationInstructions> {
        const response = await this.getImplementationInstructionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Report the status of a link implementation
     * Report implementation status
     */
    async reportImplementationStatusRaw(requestParameters: ReportImplementationStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReportImplementationStatus200Response>> {
        if (requestParameters['reportImplementationStatusRequest'] == null) {
            throw new runtime.RequiredError(
                'reportImplementationStatusRequest',
                'Required parameter "reportImplementationStatusRequest" was null or undefined when calling reportImplementationStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/webhook/implement-link`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReportImplementationStatusRequestToJSON(requestParameters['reportImplementationStatusRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReportImplementationStatus200ResponseFromJSON(jsonValue));
    }

    /**
     * Report the status of a link implementation
     * Report implementation status
     */
    async reportImplementationStatus(requestParameters: ReportImplementationStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReportImplementationStatus200Response> {
        const response = await this.reportImplementationStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
