/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKeyResponse
 */
export interface ApiKeyResponse {
    /**
     * API key identifier
     * @type {string}
     * @memberof ApiKeyResponse
     */
    id: string;
    /**
     * API key name
     * @type {string}
     * @memberof ApiKeyResponse
     */
    name: string;
    /**
     * The API key (only returned on creation)
     * @type {string}
     * @memberof ApiKeyResponse
     */
    key: string;
    /**
     * Creation timestamp
     * @type {Date}
     * @memberof ApiKeyResponse
     */
    createdAt: Date;
    /**
     * Expiration timestamp
     * @type {Date}
     * @memberof ApiKeyResponse
     */
    expiresAt?: Date | null;
    /**
     * Whether the key is active
     * @type {boolean}
     * @memberof ApiKeyResponse
     */
    isActive: boolean;
}

/**
 * Check if a given object implements the ApiKeyResponse interface.
 */
export function instanceOfApiKeyResponse(value: object): value is ApiKeyResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function ApiKeyResponseFromJSON(json: any): ApiKeyResponse {
    return ApiKeyResponseFromJSONTyped(json, false);
}

export function ApiKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'key': json['key'],
        'createdAt': (new Date(json['createdAt'])),
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'isActive': json['isActive'],
    };
}

export function ApiKeyResponseToJSON(json: any): ApiKeyResponse {
    return ApiKeyResponseToJSONTyped(json, false);
}

export function ApiKeyResponseToJSONTyped(value?: ApiKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'key': value['key'],
        'createdAt': value['createdAt'].toISOString(),
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'isActive': value['isActive'],
    };
}

