/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeResult
 */
export interface ChangeResult {
    /**
     * URL of the page
     * @type {string}
     * @memberof ChangeResult
     */
    pageUrl: string;
    /**
     * Change status
     * @type {string}
     * @memberof ChangeResult
     */
    changeStatus: ChangeResultChangeStatusEnum;
    /**
     * Page visibility
     * @type {string}
     * @memberof ChangeResult
     */
    visibility: ChangeResultVisibilityEnum;
    /**
     * Previous scrape timestamp
     * @type {Date}
     * @memberof ChangeResult
     */
    previousScrapeAt?: Date;
}


/**
 * @export
 */
export const ChangeResultChangeStatusEnum = {
    Same: 'same',
    Changed: 'changed',
    NotFound: 'not_found'
} as const;
export type ChangeResultChangeStatusEnum = typeof ChangeResultChangeStatusEnum[keyof typeof ChangeResultChangeStatusEnum];

/**
 * @export
 */
export const ChangeResultVisibilityEnum = {
    Visible: 'visible',
    Hidden: 'hidden',
    Error: 'error'
} as const;
export type ChangeResultVisibilityEnum = typeof ChangeResultVisibilityEnum[keyof typeof ChangeResultVisibilityEnum];


/**
 * Check if a given object implements the ChangeResult interface.
 */
export function instanceOfChangeResult(value: object): value is ChangeResult {
    if (!('pageUrl' in value) || value['pageUrl'] === undefined) return false;
    if (!('changeStatus' in value) || value['changeStatus'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    return true;
}

export function ChangeResultFromJSON(json: any): ChangeResult {
    return ChangeResultFromJSONTyped(json, false);
}

export function ChangeResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeResult {
    if (json == null) {
        return json;
    }
    return {
        
        'pageUrl': json['pageUrl'],
        'changeStatus': json['changeStatus'],
        'visibility': json['visibility'],
        'previousScrapeAt': json['previousScrapeAt'] == null ? undefined : (new Date(json['previousScrapeAt'])),
    };
}

export function ChangeResultToJSON(json: any): ChangeResult {
    return ChangeResultToJSONTyped(json, false);
}

export function ChangeResultToJSONTyped(value?: ChangeResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageUrl': value['pageUrl'],
        'changeStatus': value['changeStatus'],
        'visibility': value['visibility'],
        'previousScrapeAt': value['previousScrapeAt'] == null ? value['previousScrapeAt'] : value['previousScrapeAt'].toISOString(),
    };
}

