/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChangeResult } from './ChangeResult';
import {
    ChangeResultFromJSON,
    ChangeResultFromJSONTyped,
    ChangeResultToJSON,
    ChangeResultToJSONTyped,
} from './ChangeResult';

/**
 * 
 * @export
 * @interface ContentVerification
 */
export interface ContentVerification {
    /**
     * Whether it's safe to implement the link
     * @type {boolean}
     * @memberof ContentVerification
     */
    safe: boolean;
    /**
     * Reason for the verification result
     * @type {string}
     * @memberof ContentVerification
     */
    reason: string;
    /**
     * 
     * @type {ChangeResult}
     * @memberof ContentVerification
     */
    changeResult?: ChangeResult;
}

/**
 * Check if a given object implements the ContentVerification interface.
 */
export function instanceOfContentVerification(value: object): value is ContentVerification {
    if (!('safe' in value) || value['safe'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function ContentVerificationFromJSON(json: any): ContentVerification {
    return ContentVerificationFromJSONTyped(json, false);
}

export function ContentVerificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentVerification {
    if (json == null) {
        return json;
    }
    return {
        
        'safe': json['safe'],
        'reason': json['reason'],
        'changeResult': json['changeResult'] == null ? undefined : ChangeResultFromJSON(json['changeResult']),
    };
}

export function ContentVerificationToJSON(json: any): ContentVerification {
    return ContentVerificationToJSONTyped(json, false);
}

export function ContentVerificationToJSONTyped(value?: ContentVerification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'safe': value['safe'],
        'reason': value['reason'],
        'changeResult': ChangeResultToJSON(value['changeResult']),
    };
}

