/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Crawl
 */
export interface Crawl {
    /**
     * Unique crawl identifier
     * @type {string}
     * @memberof Crawl
     */
    id: string;
    /**
     * Project identifier
     * @type {string}
     * @memberof Crawl
     */
    projectId: string;
    /**
     * Crawl status
     * @type {string}
     * @memberof Crawl
     */
    status: CrawlStatusEnum;
    /**
     * Crawl start timestamp
     * @type {Date}
     * @memberof Crawl
     */
    startedAt: Date;
    /**
     * Crawl completion timestamp
     * @type {Date}
     * @memberof Crawl
     */
    completedAt?: Date;
    /**
     * Number of pages crawled
     * @type {number}
     * @memberof Crawl
     */
    pagesCrawled?: number;
    /**
     * Error message if crawl failed
     * @type {string}
     * @memberof Crawl
     */
    errorMessage?: string;
}


/**
 * @export
 */
export const CrawlStatusEnum = {
    Pending: 'pending',
    InProgress: 'in_progress',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type CrawlStatusEnum = typeof CrawlStatusEnum[keyof typeof CrawlStatusEnum];


/**
 * Check if a given object implements the Crawl interface.
 */
export function instanceOfCrawl(value: object): value is Crawl {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    return true;
}

export function CrawlFromJSON(json: any): Crawl {
    return CrawlFromJSONTyped(json, false);
}

export function CrawlFromJSONTyped(json: any, ignoreDiscriminator: boolean): Crawl {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['projectId'],
        'status': json['status'],
        'startedAt': (new Date(json['startedAt'])),
        'completedAt': json['completedAt'] == null ? undefined : (new Date(json['completedAt'])),
        'pagesCrawled': json['pagesCrawled'] == null ? undefined : json['pagesCrawled'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
    };
}

export function CrawlToJSON(json: any): Crawl {
    return CrawlToJSONTyped(json, false);
}

export function CrawlToJSONTyped(value?: Crawl | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'projectId': value['projectId'],
        'status': value['status'],
        'startedAt': value['startedAt'].toISOString(),
        'completedAt': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'pagesCrawled': value['pagesCrawled'],
        'errorMessage': value['errorMessage'],
    };
}

