/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetUserInfo200ResponseLinks } from './GetUserInfo200ResponseLinks';
import {
    GetUserInfo200ResponseLinksFromJSON,
    GetUserInfo200ResponseLinksFromJSONTyped,
    GetUserInfo200ResponseLinksToJSON,
    GetUserInfo200ResponseLinksToJSONTyped,
} from './GetUserInfo200ResponseLinks';
import type { GetUserInfo200ResponseUser } from './GetUserInfo200ResponseUser';
import {
    GetUserInfo200ResponseUserFromJSON,
    GetUserInfo200ResponseUserFromJSONTyped,
    GetUserInfo200ResponseUserToJSON,
    GetUserInfo200ResponseUserToJSONTyped,
} from './GetUserInfo200ResponseUser';

/**
 * 
 * @export
 * @interface GetUserInfo200Response
 */
export interface GetUserInfo200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetUserInfo200Response
     */
    success?: boolean;
    /**
     * 
     * @type {GetUserInfo200ResponseUser}
     * @memberof GetUserInfo200Response
     */
    user?: GetUserInfo200ResponseUser;
    /**
     * 
     * @type {GetUserInfo200ResponseLinks}
     * @memberof GetUserInfo200Response
     */
    links?: GetUserInfo200ResponseLinks;
    /**
     * 
     * @type {number}
     * @memberof GetUserInfo200Response
     */
    projectsCount?: number;
    /**
     * Recent usage (pages indexed in last 30 days)
     * @type {number}
     * @memberof GetUserInfo200Response
     */
    recentUsage?: number;
}

/**
 * Check if a given object implements the GetUserInfo200Response interface.
 */
export function instanceOfGetUserInfo200Response(value: object): value is GetUserInfo200Response {
    return true;
}

export function GetUserInfo200ResponseFromJSON(json: any): GetUserInfo200Response {
    return GetUserInfo200ResponseFromJSONTyped(json, false);
}

export function GetUserInfo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserInfo200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'user': json['user'] == null ? undefined : GetUserInfo200ResponseUserFromJSON(json['user']),
        'links': json['links'] == null ? undefined : GetUserInfo200ResponseLinksFromJSON(json['links']),
        'projectsCount': json['projectsCount'] == null ? undefined : json['projectsCount'],
        'recentUsage': json['recentUsage'] == null ? undefined : json['recentUsage'],
    };
}

export function GetUserInfo200ResponseToJSON(json: any): GetUserInfo200Response {
    return GetUserInfo200ResponseToJSONTyped(json, false);
}

export function GetUserInfo200ResponseToJSONTyped(value?: GetUserInfo200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'user': GetUserInfo200ResponseUserToJSON(value['user']),
        'links': GetUserInfo200ResponseLinksToJSON(value['links']),
        'projectsCount': value['projectsCount'],
        'recentUsage': value['recentUsage'],
    };
}

