/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserInfo200ResponseLinks
 */
export interface GetUserInfo200ResponseLinks {
    /**
     * 
     * @type {number}
     * @memberof GetUserInfo200ResponseLinks
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUserInfo200ResponseLinks
     */
    used?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUserInfo200ResponseLinks
     */
    remaining?: number;
}

/**
 * Check if a given object implements the GetUserInfo200ResponseLinks interface.
 */
export function instanceOfGetUserInfo200ResponseLinks(value: object): value is GetUserInfo200ResponseLinks {
    return true;
}

export function GetUserInfo200ResponseLinksFromJSON(json: any): GetUserInfo200ResponseLinks {
    return GetUserInfo200ResponseLinksFromJSONTyped(json, false);
}

export function GetUserInfo200ResponseLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserInfo200ResponseLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'used': json['used'] == null ? undefined : json['used'],
        'remaining': json['remaining'] == null ? undefined : json['remaining'],
    };
}

export function GetUserInfo200ResponseLinksToJSON(json: any): GetUserInfo200ResponseLinks {
    return GetUserInfo200ResponseLinksToJSONTyped(json, false);
}

export function GetUserInfo200ResponseLinksToJSONTyped(value?: GetUserInfo200ResponseLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'used': value['used'],
        'remaining': value['remaining'],
    };
}

