/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserInfo200ResponseUser
 */
export interface GetUserInfo200ResponseUser {
    /**
     * 
     * @type {string}
     * @memberof GetUserInfo200ResponseUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserInfo200ResponseUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserInfo200ResponseUser
     */
    name?: string | null;
}

/**
 * Check if a given object implements the GetUserInfo200ResponseUser interface.
 */
export function instanceOfGetUserInfo200ResponseUser(value: object): value is GetUserInfo200ResponseUser {
    return true;
}

export function GetUserInfo200ResponseUserFromJSON(json: any): GetUserInfo200ResponseUser {
    return GetUserInfo200ResponseUserFromJSONTyped(json, false);
}

export function GetUserInfo200ResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserInfo200ResponseUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function GetUserInfo200ResponseUserToJSON(json: any): GetUserInfo200ResponseUser {
    return GetUserInfo200ResponseUserToJSONTyped(json, false);
}

export function GetUserInfo200ResponseUserToJSONTyped(value?: GetUserInfo200ResponseUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'name': value['name'],
    };
}

