/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomCredentials } from './CustomCredentials';
import {
    CustomCredentialsFromJSON,
    CustomCredentialsFromJSONTyped,
    CustomCredentialsToJSON,
    CustomCredentialsToJSONTyped,
} from './CustomCredentials';

/**
 * 
 * @export
 * @interface ImplementationRequest
 */
export interface ImplementationRequest {
    /**
     * Array of suggestion IDs to implement
     * @type {Array<string>}
     * @memberof ImplementationRequest
     */
    suggestionIds: Array<string>;
    /**
     * Platform type
     * @type {string}
     * @memberof ImplementationRequest
     */
    platform: ImplementationRequestPlatformEnum;
    /**
     * 
     * @type {CustomCredentials}
     * @memberof ImplementationRequest
     */
    credentials: CustomCredentials;
    /**
     * Skip content change detection
     * @type {boolean}
     * @memberof ImplementationRequest
     */
    skipContentVerification?: boolean;
    /**
     * Implementation method
     * @type {string}
     * @memberof ImplementationRequest
     */
    implementationMethod?: ImplementationRequestImplementationMethodEnum;
}


/**
 * @export
 */
export const ImplementationRequestPlatformEnum = {
    Custom: 'custom'
} as const;
export type ImplementationRequestPlatformEnum = typeof ImplementationRequestPlatformEnum[keyof typeof ImplementationRequestPlatformEnum];

/**
 * @export
 */
export const ImplementationRequestImplementationMethodEnum = {
    Api: 'api',
    Manual: 'manual'
} as const;
export type ImplementationRequestImplementationMethodEnum = typeof ImplementationRequestImplementationMethodEnum[keyof typeof ImplementationRequestImplementationMethodEnum];


/**
 * Check if a given object implements the ImplementationRequest interface.
 */
export function instanceOfImplementationRequest(value: object): value is ImplementationRequest {
    if (!('suggestionIds' in value) || value['suggestionIds'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('credentials' in value) || value['credentials'] === undefined) return false;
    return true;
}

export function ImplementationRequestFromJSON(json: any): ImplementationRequest {
    return ImplementationRequestFromJSONTyped(json, false);
}

export function ImplementationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImplementationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'suggestionIds': json['suggestionIds'],
        'platform': json['platform'],
        'credentials': CustomCredentialsFromJSON(json['credentials']),
        'skipContentVerification': json['skipContentVerification'] == null ? undefined : json['skipContentVerification'],
        'implementationMethod': json['implementationMethod'] == null ? undefined : json['implementationMethod'],
    };
}

export function ImplementationRequestToJSON(json: any): ImplementationRequest {
    return ImplementationRequestToJSONTyped(json, false);
}

export function ImplementationRequestToJSONTyped(value?: ImplementationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'suggestionIds': value['suggestionIds'],
        'platform': value['platform'],
        'credentials': CustomCredentialsToJSON(value['credentials']),
        'skipContentVerification': value['skipContentVerification'],
        'implementationMethod': value['implementationMethod'],
    };
}

