/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImplementationSummary } from './ImplementationSummary';
import {
    ImplementationSummaryFromJSON,
    ImplementationSummaryFromJSONTyped,
    ImplementationSummaryToJSON,
    ImplementationSummaryToJSONTyped,
} from './ImplementationSummary';
import type { ImplementationResult } from './ImplementationResult';
import {
    ImplementationResultFromJSON,
    ImplementationResultFromJSONTyped,
    ImplementationResultToJSON,
    ImplementationResultToJSONTyped,
} from './ImplementationResult';

/**
 * 
 * @export
 * @interface ImplementationResponse
 */
export interface ImplementationResponse {
    /**
     * Whether any implementations succeeded
     * @type {boolean}
     * @memberof ImplementationResponse
     */
    success: boolean;
    /**
     * Individual implementation results
     * @type {Array<ImplementationResult>}
     * @memberof ImplementationResponse
     */
    results: Array<ImplementationResult>;
    /**
     * 
     * @type {ImplementationSummary}
     * @memberof ImplementationResponse
     */
    summary: ImplementationSummary;
}

/**
 * Check if a given object implements the ImplementationResponse interface.
 */
export function instanceOfImplementationResponse(value: object): value is ImplementationResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function ImplementationResponseFromJSON(json: any): ImplementationResponse {
    return ImplementationResponseFromJSONTyped(json, false);
}

export function ImplementationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImplementationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'results': ((json['results'] as Array<any>).map(ImplementationResultFromJSON)),
        'summary': ImplementationSummaryFromJSON(json['summary']),
    };
}

export function ImplementationResponseToJSON(json: any): ImplementationResponse {
    return ImplementationResponseToJSONTyped(json, false);
}

export function ImplementationResponseToJSONTyped(value?: ImplementationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'results': ((value['results'] as Array<any>).map(ImplementationResultToJSON)),
        'summary': ImplementationSummaryToJSON(value['summary']),
    };
}

