/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Page } from './Page';
import {
    PageFromJSON,
    PageFromJSONTyped,
    PageToJSON,
    PageToJSONTyped,
} from './Page';

/**
 * 
 * @export
 * @interface ListPages200Response
 */
export interface ListPages200Response {
    /**
     * 
     * @type {Array<Page>}
     * @memberof ListPages200Response
     */
    pages?: Array<Page>;
    /**
     * 
     * @type {number}
     * @memberof ListPages200Response
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof ListPages200Response
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ListPages200Response
     */
    offset?: number;
}

/**
 * Check if a given object implements the ListPages200Response interface.
 */
export function instanceOfListPages200Response(value: object): value is ListPages200Response {
    return true;
}

export function ListPages200ResponseFromJSON(json: any): ListPages200Response {
    return ListPages200ResponseFromJSONTyped(json, false);
}

export function ListPages200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPages200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'pages': json['pages'] == null ? undefined : ((json['pages'] as Array<any>).map(PageFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
    };
}

export function ListPages200ResponseToJSON(json: any): ListPages200Response {
    return ListPages200ResponseToJSONTyped(json, false);
}

export function ListPages200ResponseToJSONTyped(value?: ListPages200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pages': value['pages'] == null ? undefined : ((value['pages'] as Array<any>).map(PageToJSON)),
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

