/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageLimitStatus
 */
export interface PageLimitStatus {
    /**
     * Page limit
     * @type {number}
     * @memberof PageLimitStatus
     */
    limit: number;
    /**
     * Pages used
     * @type {number}
     * @memberof PageLimitStatus
     */
    used: number;
    /**
     * Pages remaining
     * @type {number}
     * @memberof PageLimitStatus
     */
    remaining: number;
}

/**
 * Check if a given object implements the PageLimitStatus interface.
 */
export function instanceOfPageLimitStatus(value: object): value is PageLimitStatus {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('used' in value) || value['used'] === undefined) return false;
    if (!('remaining' in value) || value['remaining'] === undefined) return false;
    return true;
}

export function PageLimitStatusFromJSON(json: any): PageLimitStatus {
    return PageLimitStatusFromJSONTyped(json, false);
}

export function PageLimitStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageLimitStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'],
        'used': json['used'],
        'remaining': json['remaining'],
    };
}

export function PageLimitStatusToJSON(json: any): PageLimitStatus {
    return PageLimitStatusToJSONTyped(json, false);
}

export function PageLimitStatusToJSONTyped(value?: PageLimitStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'used': value['used'],
        'remaining': value['remaining'],
    };
}

