/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Page
 */
export interface Page {
    /**
     * Page identifier
     * @type {string}
     * @memberof Page
     */
    id: string;
    /**
     * Project identifier
     * @type {string}
     * @memberof Page
     */
    projectId: string;
    /**
     * Page URL
     * @type {string}
     * @memberof Page
     */
    url: string;
    /**
     * Page title
     * @type {string}
     * @memberof Page
     */
    title?: string | null;
    /**
     * Word count
     * @type {number}
     * @memberof Page
     */
    wordCount?: number | null;
    /**
     * Internal links on the page
     * @type {Array<object>}
     * @memberof Page
     */
    internalLinks?: Array<object>;
    /**
     * External links on the page
     * @type {Array<object>}
     * @memberof Page
     */
    externalLinks?: Array<object>;
    /**
     * Last sync timestamp
     * @type {Date}
     * @memberof Page
     */
    syncedAt?: Date | null;
    /**
     * Last update timestamp
     * @type {Date}
     * @memberof Page
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the Page interface.
 */
export function instanceOfPage(value: object): value is Page {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function PageFromJSON(json: any): Page {
    return PageFromJSONTyped(json, false);
}

export function PageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Page {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['projectId'],
        'url': json['url'],
        'title': json['title'] == null ? undefined : json['title'],
        'wordCount': json['wordCount'] == null ? undefined : json['wordCount'],
        'internalLinks': json['internalLinks'] == null ? undefined : json['internalLinks'],
        'externalLinks': json['externalLinks'] == null ? undefined : json['externalLinks'],
        'syncedAt': json['syncedAt'] == null ? undefined : (new Date(json['syncedAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function PageToJSON(json: any): Page {
    return PageToJSONTyped(json, false);
}

export function PageToJSONTyped(value?: Page | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'projectId': value['projectId'],
        'url': value['url'],
        'title': value['title'],
        'wordCount': value['wordCount'],
        'internalLinks': value['internalLinks'],
        'externalLinks': value['externalLinks'],
        'syncedAt': value['syncedAt'] == null ? value['syncedAt'] : value['syncedAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

