/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageAllowanceInfo
 */
export interface PageAllowanceInfo {
    /**
     * Total pages allowed (tier + packs)
     * @type {number}
     * @memberof PageAllowanceInfo
     */
    pagesTotal: number;
    /**
     * Pages currently indexed across all projects
     * @type {number}
     * @memberof PageAllowanceInfo
     */
    pagesUsed: number;
    /**
     * Remaining pages before upgrade or page pack
     * @type {number}
     * @memberof PageAllowanceInfo
     */
    pagesRemaining: number;
}

/**
 * Check if a given object implements the PageAllowanceInfo interface.
 */
export function instanceOfPageAllowanceInfo(value: object): value is PageAllowanceInfo {
    if (!('pagesTotal' in value) || value['pagesTotal'] === undefined) return false;
    if (!('pagesUsed' in value) || value['pagesUsed'] === undefined) return false;
    if (!('pagesRemaining' in value) || value['pagesRemaining'] === undefined) return false;
    return true;
}

export function PageAllowanceInfoFromJSON(json: any): PageAllowanceInfo {
    return PageAllowanceInfoFromJSONTyped(json, false);
}

export function PageAllowanceInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageAllowanceInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'pagesTotal': json['pagesTotal'],
        'pagesUsed': json['pagesUsed'],
        'pagesRemaining': json['pagesRemaining'],
    };
}

export function PageAllowanceInfoToJSON(json: any): PageAllowanceInfo {
    return PageAllowanceInfoToJSONTyped(json, false);
}

export function PageAllowanceInfoToJSONTyped(value?: PageAllowanceInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagesTotal': value['pagesTotal'],
        'pagesUsed': value['pagesUsed'],
        'pagesRemaining': value['pagesRemaining'],
    };
}

