/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectCount } from './ProjectCount';
import {
    ProjectCountFromJSON,
    ProjectCountFromJSONTyped,
    ProjectCountToJSON,
    ProjectCountToJSONTyped,
} from './ProjectCount';

/**
 * 
 * @export
 * @interface Project
 */
export interface Project {
    /**
     * Unique project identifier
     * @type {string}
     * @memberof Project
     */
    id: string;
    /**
     * Project name
     * @type {string}
     * @memberof Project
     */
    name: string;
    /**
     * Website domain URL
     * @type {string}
     * @memberof Project
     */
    domain: string;
    /**
     * User who owns the project
     * @type {string}
     * @memberof Project
     */
    userId: string;
    /**
     * Natural language prompt for crawling
     * @type {string}
     * @memberof Project
     */
    prompt?: string;
    /**
     * Search query for targeted crawling
     * @type {string}
     * @memberof Project
     */
    searchQuery?: string;
    /**
     * How to handle sitemaps
     * @type {string}
     * @memberof Project
     */
    sitemapMode?: ProjectSitemapModeEnum;
    /**
     * Whether to include subdomains
     * @type {boolean}
     * @memberof Project
     */
    includeSubdomains?: boolean;
    /**
     * Whether to ignore URL query parameters
     * @type {boolean}
     * @memberof Project
     */
    ignoreQueryParams?: boolean;
    /**
     * Maximum crawl depth
     * @type {number}
     * @memberof Project
     */
    maxDiscoveryDepth?: number;
    /**
     * Paths to exclude from crawling
     * @type {Array<string>}
     * @memberof Project
     */
    excludePaths?: Array<string>;
    /**
     * Specific paths to include
     * @type {Array<string>}
     * @memberof Project
     */
    includePaths?: Array<string>;
    /**
     * Whether to crawl the entire domain
     * @type {boolean}
     * @memberof Project
     */
    crawlEntireDomain?: boolean;
    /**
     * Whether to allow external links
     * @type {boolean}
     * @memberof Project
     */
    allowExternalLinks?: boolean;
    /**
     * Maximum number of pages to crawl
     * @type {number}
     * @memberof Project
     */
    maxPages?: number;
    /**
     * Delay between crawl requests (ms)
     * @type {number}
     * @memberof Project
     */
    crawlDelay?: number;
    /**
     * Maximum concurrent crawl requests
     * @type {number}
     * @memberof Project
     */
    crawlMaxConcurrency?: number;
    /**
     * Whether to extract only main content
     * @type {boolean}
     * @memberof Project
     */
    onlyMainContent?: boolean;
    /**
     * Custom headers for crawling
     * @type {{ [key: string]: string; }}
     * @memberof Project
     */
    customHeaders?: { [key: string]: string; };
    /**
     * Wait time for page load (ms)
     * @type {number}
     * @memberof Project
     */
    waitFor?: number;
    /**
     * Whether to block ads
     * @type {boolean}
     * @memberof Project
     */
    blockAds?: boolean;
    /**
     * Proxy mode for crawling
     * @type {string}
     * @memberof Project
     */
    proxyMode?: ProjectProxyModeEnum;
    /**
     * Whether to use AI reranking
     * @type {boolean}
     * @memberof Project
     */
    useReranking?: boolean;
    /**
     * Whether to enable change tracking
     * @type {boolean}
     * @memberof Project
     */
    enableChangeTracking?: boolean;
    /**
     * Project creation timestamp
     * @type {Date}
     * @memberof Project
     */
    createdAt: Date;
    /**
     * Last update timestamp
     * @type {Date}
     * @memberof Project
     */
    updatedAt: Date;
    /**
     * 
     * @type {ProjectCount}
     * @memberof Project
     */
    count?: ProjectCount;
}


/**
 * @export
 */
export const ProjectSitemapModeEnum = {
    Include: 'include',
    Exclude: 'exclude',
    Only: 'only'
} as const;
export type ProjectSitemapModeEnum = typeof ProjectSitemapModeEnum[keyof typeof ProjectSitemapModeEnum];

/**
 * @export
 */
export const ProjectProxyModeEnum = {
    Auto: 'auto',
    Residential: 'residential',
    Datacenter: 'datacenter'
} as const;
export type ProjectProxyModeEnum = typeof ProjectProxyModeEnum[keyof typeof ProjectProxyModeEnum];


/**
 * Check if a given object implements the Project interface.
 */
export function instanceOfProject(value: object): value is Project {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ProjectFromJSON(json: any): Project {
    return ProjectFromJSONTyped(json, false);
}

export function ProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Project {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'domain': json['domain'],
        'userId': json['userId'],
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'searchQuery': json['searchQuery'] == null ? undefined : json['searchQuery'],
        'sitemapMode': json['sitemapMode'] == null ? undefined : json['sitemapMode'],
        'includeSubdomains': json['includeSubdomains'] == null ? undefined : json['includeSubdomains'],
        'ignoreQueryParams': json['ignoreQueryParams'] == null ? undefined : json['ignoreQueryParams'],
        'maxDiscoveryDepth': json['maxDiscoveryDepth'] == null ? undefined : json['maxDiscoveryDepth'],
        'excludePaths': json['excludePaths'] == null ? undefined : json['excludePaths'],
        'includePaths': json['includePaths'] == null ? undefined : json['includePaths'],
        'crawlEntireDomain': json['crawlEntireDomain'] == null ? undefined : json['crawlEntireDomain'],
        'allowExternalLinks': json['allowExternalLinks'] == null ? undefined : json['allowExternalLinks'],
        'maxPages': json['maxPages'] == null ? undefined : json['maxPages'],
        'crawlDelay': json['crawlDelay'] == null ? undefined : json['crawlDelay'],
        'crawlMaxConcurrency': json['crawlMaxConcurrency'] == null ? undefined : json['crawlMaxConcurrency'],
        'onlyMainContent': json['onlyMainContent'] == null ? undefined : json['onlyMainContent'],
        'customHeaders': json['customHeaders'] == null ? undefined : json['customHeaders'],
        'waitFor': json['waitFor'] == null ? undefined : json['waitFor'],
        'blockAds': json['blockAds'] == null ? undefined : json['blockAds'],
        'proxyMode': json['proxyMode'] == null ? undefined : json['proxyMode'],
        'useReranking': json['useReranking'] == null ? undefined : json['useReranking'],
        'enableChangeTracking': json['enableChangeTracking'] == null ? undefined : json['enableChangeTracking'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'count': json['_count'] == null ? undefined : ProjectCountFromJSON(json['_count']),
    };
}

export function ProjectToJSON(json: any): Project {
    return ProjectToJSONTyped(json, false);
}

export function ProjectToJSONTyped(value?: Project | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'domain': value['domain'],
        'userId': value['userId'],
        'prompt': value['prompt'],
        'searchQuery': value['searchQuery'],
        'sitemapMode': value['sitemapMode'],
        'includeSubdomains': value['includeSubdomains'],
        'ignoreQueryParams': value['ignoreQueryParams'],
        'maxDiscoveryDepth': value['maxDiscoveryDepth'],
        'excludePaths': value['excludePaths'],
        'includePaths': value['includePaths'],
        'crawlEntireDomain': value['crawlEntireDomain'],
        'allowExternalLinks': value['allowExternalLinks'],
        'maxPages': value['maxPages'],
        'crawlDelay': value['crawlDelay'],
        'crawlMaxConcurrency': value['crawlMaxConcurrency'],
        'onlyMainContent': value['onlyMainContent'],
        'customHeaders': value['customHeaders'],
        'waitFor': value['waitFor'],
        'blockAds': value['blockAds'],
        'proxyMode': value['proxyMode'],
        'useReranking': value['useReranking'],
        'enableChangeTracking': value['enableChangeTracking'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        '_count': ProjectCountToJSON(value['count']),
    };
}

