/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectAnalyticsImplementationStats
 */
export interface ProjectAnalyticsImplementationStats {
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsImplementationStats
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsImplementationStats
     */
    success?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsImplementationStats
     */
    failed?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsImplementationStats
     */
    pending?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsImplementationStats
     */
    inProgress?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsImplementationStats
     */
    successRate?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsImplementationStats
     */
    avgCreditsUsed?: number;
    /**
     * 
     * @type {object}
     * @memberof ProjectAnalyticsImplementationStats
     */
    platformBreakdown?: object;
}

/**
 * Check if a given object implements the ProjectAnalyticsImplementationStats interface.
 */
export function instanceOfProjectAnalyticsImplementationStats(value: object): value is ProjectAnalyticsImplementationStats {
    return true;
}

export function ProjectAnalyticsImplementationStatsFromJSON(json: any): ProjectAnalyticsImplementationStats {
    return ProjectAnalyticsImplementationStatsFromJSONTyped(json, false);
}

export function ProjectAnalyticsImplementationStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectAnalyticsImplementationStats {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'success': json['success'] == null ? undefined : json['success'],
        'failed': json['failed'] == null ? undefined : json['failed'],
        'pending': json['pending'] == null ? undefined : json['pending'],
        'inProgress': json['inProgress'] == null ? undefined : json['inProgress'],
        'successRate': json['successRate'] == null ? undefined : json['successRate'],
        'avgCreditsUsed': json['avgCreditsUsed'] == null ? undefined : json['avgCreditsUsed'],
        'platformBreakdown': json['platformBreakdown'] == null ? undefined : json['platformBreakdown'],
    };
}

export function ProjectAnalyticsImplementationStatsToJSON(json: any): ProjectAnalyticsImplementationStats {
    return ProjectAnalyticsImplementationStatsToJSONTyped(json, false);
}

export function ProjectAnalyticsImplementationStatsToJSONTyped(value?: ProjectAnalyticsImplementationStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'success': value['success'],
        'failed': value['failed'],
        'pending': value['pending'],
        'inProgress': value['inProgress'],
        'successRate': value['successRate'],
        'avgCreditsUsed': value['avgCreditsUsed'],
        'platformBreakdown': value['platformBreakdown'],
    };
}

