/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreditBalanceInfo } from './CreditBalanceInfo';
import {
    CreditBalanceInfoFromJSON,
    CreditBalanceInfoFromJSONTyped,
    CreditBalanceInfoToJSON,
    CreditBalanceInfoToJSONTyped,
} from './CreditBalanceInfo';

/**
 * 
 * @export
 * @interface AddCredits200Response
 */
export interface AddCredits200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AddCredits200Response
     */
    success?: boolean;
    /**
     * 
     * @type {CreditBalanceInfo}
     * @memberof AddCredits200Response
     */
    balance?: CreditBalanceInfo;
    /**
     * 
     * @type {string}
     * @memberof AddCredits200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the AddCredits200Response interface.
 */
export function instanceOfAddCredits200Response(value: object): value is AddCredits200Response {
    return true;
}

export function AddCredits200ResponseFromJSON(json: any): AddCredits200Response {
    return AddCredits200ResponseFromJSONTyped(json, false);
}

export function AddCredits200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddCredits200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'balance': json['balance'] == null ? undefined : CreditBalanceInfoFromJSON(json['balance']),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function AddCredits200ResponseToJSON(json: any): AddCredits200Response {
    return AddCredits200ResponseToJSONTyped(json, false);
}

export function AddCredits200ResponseToJSONTyped(value?: AddCredits200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'balance': CreditBalanceInfoToJSON(value['balance']),
        'message': value['message'],
    };
}

