/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutoRechargeSettings
 */
export interface AutoRechargeSettings {
    /**
     * Whether auto-recharge is enabled
     * @type {boolean}
     * @memberof AutoRechargeSettings
     */
    enabled: boolean;
    /**
     * Credit threshold for auto-recharge
     * @type {number}
     * @memberof AutoRechargeSettings
     */
    threshold: number;
    /**
     * Amount to recharge
     * @type {number}
     * @memberof AutoRechargeSettings
     */
    amount: number;
}

/**
 * Check if a given object implements the AutoRechargeSettings interface.
 */
export function instanceOfAutoRechargeSettings(value: object): value is AutoRechargeSettings {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('threshold' in value) || value['threshold'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function AutoRechargeSettingsFromJSON(json: any): AutoRechargeSettings {
    return AutoRechargeSettingsFromJSONTyped(json, false);
}

export function AutoRechargeSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoRechargeSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'threshold': json['threshold'],
        'amount': json['amount'],
    };
}

export function AutoRechargeSettingsToJSON(json: any): AutoRechargeSettings {
    return AutoRechargeSettingsToJSONTyped(json, false);
}

export function AutoRechargeSettingsToJSONTyped(value?: AutoRechargeSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'threshold': value['threshold'],
        'amount': value['amount'],
    };
}

