/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProjectRequest
 */
export interface CreateProjectRequest {
    /**
     * Project name
     * @type {string}
     * @memberof CreateProjectRequest
     */
    name: string;
    /**
     * Website domain URL
     * @type {string}
     * @memberof CreateProjectRequest
     */
    domain: string;
    /**
     * Natural language prompt for crawling
     * @type {string}
     * @memberof CreateProjectRequest
     */
    prompt?: string;
    /**
     * Search query for targeted crawling
     * @type {string}
     * @memberof CreateProjectRequest
     */
    searchQuery?: string;
    /**
     * How to handle sitemaps
     * @type {string}
     * @memberof CreateProjectRequest
     */
    sitemapMode?: CreateProjectRequestSitemapModeEnum;
    /**
     * Whether to include subdomains
     * @type {boolean}
     * @memberof CreateProjectRequest
     */
    includeSubdomains?: boolean;
    /**
     * Whether to ignore URL query parameters
     * @type {boolean}
     * @memberof CreateProjectRequest
     */
    ignoreQueryParams?: boolean;
    /**
     * Maximum crawl depth
     * @type {number}
     * @memberof CreateProjectRequest
     */
    maxDiscoveryDepth?: number;
    /**
     * Paths to exclude from crawling
     * @type {Array<string>}
     * @memberof CreateProjectRequest
     */
    excludePaths?: Array<string>;
    /**
     * Specific paths to include
     * @type {Array<string>}
     * @memberof CreateProjectRequest
     */
    includePaths?: Array<string>;
    /**
     * Whether to crawl the entire domain
     * @type {boolean}
     * @memberof CreateProjectRequest
     */
    crawlEntireDomain?: boolean;
    /**
     * Whether to allow external links
     * @type {boolean}
     * @memberof CreateProjectRequest
     */
    allowExternalLinks?: boolean;
    /**
     * Maximum number of pages to crawl
     * @type {number}
     * @memberof CreateProjectRequest
     */
    maxPages?: number;
    /**
     * Delay between crawl requests (ms)
     * @type {number}
     * @memberof CreateProjectRequest
     */
    crawlDelay?: number;
    /**
     * Maximum concurrent crawl requests
     * @type {number}
     * @memberof CreateProjectRequest
     */
    crawlMaxConcurrency?: number;
    /**
     * Whether to extract only main content
     * @type {boolean}
     * @memberof CreateProjectRequest
     */
    onlyMainContent?: boolean;
    /**
     * Custom headers for crawling
     * @type {{ [key: string]: string; }}
     * @memberof CreateProjectRequest
     */
    customHeaders?: { [key: string]: string; };
    /**
     * Wait time for page load (ms)
     * @type {number}
     * @memberof CreateProjectRequest
     */
    waitFor?: number;
    /**
     * Whether to block ads
     * @type {boolean}
     * @memberof CreateProjectRequest
     */
    blockAds?: boolean;
    /**
     * Proxy mode for crawling
     * @type {string}
     * @memberof CreateProjectRequest
     */
    proxyMode?: CreateProjectRequestProxyModeEnum;
    /**
     * Whether to use AI reranking
     * @type {boolean}
     * @memberof CreateProjectRequest
     */
    useReranking?: boolean;
    /**
     * Whether to enable change tracking
     * @type {boolean}
     * @memberof CreateProjectRequest
     */
    enableChangeTracking?: boolean;
}


/**
 * @export
 */
export const CreateProjectRequestSitemapModeEnum = {
    Include: 'include',
    Exclude: 'exclude',
    Only: 'only'
} as const;
export type CreateProjectRequestSitemapModeEnum = typeof CreateProjectRequestSitemapModeEnum[keyof typeof CreateProjectRequestSitemapModeEnum];

/**
 * @export
 */
export const CreateProjectRequestProxyModeEnum = {
    Auto: 'auto',
    Residential: 'residential',
    Datacenter: 'datacenter'
} as const;
export type CreateProjectRequestProxyModeEnum = typeof CreateProjectRequestProxyModeEnum[keyof typeof CreateProjectRequestProxyModeEnum];


/**
 * Check if a given object implements the CreateProjectRequest interface.
 */
export function instanceOfCreateProjectRequest(value: object): value is CreateProjectRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    return true;
}

export function CreateProjectRequestFromJSON(json: any): CreateProjectRequest {
    return CreateProjectRequestFromJSONTyped(json, false);
}

export function CreateProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'domain': json['domain'],
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'searchQuery': json['searchQuery'] == null ? undefined : json['searchQuery'],
        'sitemapMode': json['sitemapMode'] == null ? undefined : json['sitemapMode'],
        'includeSubdomains': json['includeSubdomains'] == null ? undefined : json['includeSubdomains'],
        'ignoreQueryParams': json['ignoreQueryParams'] == null ? undefined : json['ignoreQueryParams'],
        'maxDiscoveryDepth': json['maxDiscoveryDepth'] == null ? undefined : json['maxDiscoveryDepth'],
        'excludePaths': json['excludePaths'] == null ? undefined : json['excludePaths'],
        'includePaths': json['includePaths'] == null ? undefined : json['includePaths'],
        'crawlEntireDomain': json['crawlEntireDomain'] == null ? undefined : json['crawlEntireDomain'],
        'allowExternalLinks': json['allowExternalLinks'] == null ? undefined : json['allowExternalLinks'],
        'maxPages': json['maxPages'] == null ? undefined : json['maxPages'],
        'crawlDelay': json['crawlDelay'] == null ? undefined : json['crawlDelay'],
        'crawlMaxConcurrency': json['crawlMaxConcurrency'] == null ? undefined : json['crawlMaxConcurrency'],
        'onlyMainContent': json['onlyMainContent'] == null ? undefined : json['onlyMainContent'],
        'customHeaders': json['customHeaders'] == null ? undefined : json['customHeaders'],
        'waitFor': json['waitFor'] == null ? undefined : json['waitFor'],
        'blockAds': json['blockAds'] == null ? undefined : json['blockAds'],
        'proxyMode': json['proxyMode'] == null ? undefined : json['proxyMode'],
        'useReranking': json['useReranking'] == null ? undefined : json['useReranking'],
        'enableChangeTracking': json['enableChangeTracking'] == null ? undefined : json['enableChangeTracking'],
    };
}

export function CreateProjectRequestToJSON(json: any): CreateProjectRequest {
    return CreateProjectRequestToJSONTyped(json, false);
}

export function CreateProjectRequestToJSONTyped(value?: CreateProjectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'domain': value['domain'],
        'prompt': value['prompt'],
        'searchQuery': value['searchQuery'],
        'sitemapMode': value['sitemapMode'],
        'includeSubdomains': value['includeSubdomains'],
        'ignoreQueryParams': value['ignoreQueryParams'],
        'maxDiscoveryDepth': value['maxDiscoveryDepth'],
        'excludePaths': value['excludePaths'],
        'includePaths': value['includePaths'],
        'crawlEntireDomain': value['crawlEntireDomain'],
        'allowExternalLinks': value['allowExternalLinks'],
        'maxPages': value['maxPages'],
        'crawlDelay': value['crawlDelay'],
        'crawlMaxConcurrency': value['crawlMaxConcurrency'],
        'onlyMainContent': value['onlyMainContent'],
        'customHeaders': value['customHeaders'],
        'waitFor': value['waitFor'],
        'blockAds': value['blockAds'],
        'proxyMode': value['proxyMode'],
        'useReranking': value['useReranking'],
        'enableChangeTracking': value['enableChangeTracking'],
    };
}

