/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreditRatesExamplesApiQueries100 } from './CreditRatesExamplesApiQueries100';
import {
    CreditRatesExamplesApiQueries100FromJSON,
    CreditRatesExamplesApiQueries100FromJSONTyped,
    CreditRatesExamplesApiQueries100ToJSON,
    CreditRatesExamplesApiQueries100ToJSONTyped,
} from './CreditRatesExamplesApiQueries100';
import type { CreditRatesExamplesCrawl100Pages } from './CreditRatesExamplesCrawl100Pages';
import {
    CreditRatesExamplesCrawl100PagesFromJSON,
    CreditRatesExamplesCrawl100PagesFromJSONTyped,
    CreditRatesExamplesCrawl100PagesToJSON,
    CreditRatesExamplesCrawl100PagesToJSONTyped,
} from './CreditRatesExamplesCrawl100Pages';

/**
 * 
 * @export
 * @interface CreditRatesExamples
 */
export interface CreditRatesExamples {
    /**
     * 
     * @type {CreditRatesExamplesCrawl100Pages}
     * @memberof CreditRatesExamples
     */
    crawl100Pages?: CreditRatesExamplesCrawl100Pages;
    /**
     * 
     * @type {CreditRatesExamplesCrawl100Pages}
     * @memberof CreditRatesExamples
     */
    implement50Links?: CreditRatesExamplesCrawl100Pages;
    /**
     * 
     * @type {CreditRatesExamplesApiQueries100}
     * @memberof CreditRatesExamples
     */
    apiQueries100?: CreditRatesExamplesApiQueries100;
}

/**
 * Check if a given object implements the CreditRatesExamples interface.
 */
export function instanceOfCreditRatesExamples(value: object): value is CreditRatesExamples {
    return true;
}

export function CreditRatesExamplesFromJSON(json: any): CreditRatesExamples {
    return CreditRatesExamplesFromJSONTyped(json, false);
}

export function CreditRatesExamplesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditRatesExamples {
    if (json == null) {
        return json;
    }
    return {
        
        'crawl100Pages': json['crawl100Pages'] == null ? undefined : CreditRatesExamplesCrawl100PagesFromJSON(json['crawl100Pages']),
        'implement50Links': json['implement50Links'] == null ? undefined : CreditRatesExamplesCrawl100PagesFromJSON(json['implement50Links']),
        'apiQueries100': json['apiQueries100'] == null ? undefined : CreditRatesExamplesApiQueries100FromJSON(json['apiQueries100']),
    };
}

export function CreditRatesExamplesToJSON(json: any): CreditRatesExamples {
    return CreditRatesExamplesToJSONTyped(json, false);
}

export function CreditRatesExamplesToJSONTyped(value?: CreditRatesExamples | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'crawl100Pages': CreditRatesExamplesCrawl100PagesToJSON(value['crawl100Pages']),
        'implement50Links': CreditRatesExamplesCrawl100PagesToJSON(value['implement50Links']),
        'apiQueries100': CreditRatesExamplesApiQueries100ToJSON(value['apiQueries100']),
    };
}

