/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsageHistoryItem } from './UsageHistoryItem';
import {
    UsageHistoryItemFromJSON,
    UsageHistoryItemFromJSONTyped,
    UsageHistoryItemToJSON,
    UsageHistoryItemToJSONTyped,
} from './UsageHistoryItem';
import type { CreditBalanceInfo } from './CreditBalanceInfo';
import {
    CreditBalanceInfoFromJSON,
    CreditBalanceInfoFromJSONTyped,
    CreditBalanceInfoToJSON,
    CreditBalanceInfoToJSONTyped,
} from './CreditBalanceInfo';
import type { SpendingLimitStatus } from './SpendingLimitStatus';
import {
    SpendingLimitStatusFromJSON,
    SpendingLimitStatusFromJSONTyped,
    SpendingLimitStatusToJSON,
    SpendingLimitStatusToJSONTyped,
} from './SpendingLimitStatus';
import type { PeriodCharges } from './PeriodCharges';
import {
    PeriodChargesFromJSON,
    PeriodChargesFromJSONTyped,
    PeriodChargesToJSON,
    PeriodChargesToJSONTyped,
} from './PeriodCharges';
import type { AutoRechargeSettings } from './AutoRechargeSettings';
import {
    AutoRechargeSettingsFromJSON,
    AutoRechargeSettingsFromJSONTyped,
    AutoRechargeSettingsToJSON,
    AutoRechargeSettingsToJSONTyped,
} from './AutoRechargeSettings';
import type { PageLimitStatus } from './PageLimitStatus';
import {
    PageLimitStatusFromJSON,
    PageLimitStatusFromJSONTyped,
    PageLimitStatusToJSON,
    PageLimitStatusToJSONTyped,
} from './PageLimitStatus';

/**
 * 
 * @export
 * @interface CreditBalance
 */
export interface CreditBalance {
    /**
     * 
     * @type {boolean}
     * @memberof CreditBalance
     */
    success: boolean;
    /**
     * 
     * @type {CreditBalanceInfo}
     * @memberof CreditBalance
     */
    balance: CreditBalanceInfo;
    /**
     * 
     * @type {PageLimitStatus}
     * @memberof CreditBalance
     */
    pageLimit: PageLimitStatus;
    /**
     * 
     * @type {SpendingLimitStatus}
     * @memberof CreditBalance
     */
    spendingLimit: SpendingLimitStatus;
    /**
     * 
     * @type {AutoRechargeSettings}
     * @memberof CreditBalance
     */
    autoRecharge: AutoRechargeSettings;
    /**
     * 
     * @type {PeriodCharges}
     * @memberof CreditBalance
     */
    currentPeriod: PeriodCharges;
    /**
     * Usage history (if requested)
     * @type {Array<UsageHistoryItem>}
     * @memberof CreditBalance
     */
    usageHistory?: Array<UsageHistoryItem>;
}

/**
 * Check if a given object implements the CreditBalance interface.
 */
export function instanceOfCreditBalance(value: object): value is CreditBalance {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    if (!('pageLimit' in value) || value['pageLimit'] === undefined) return false;
    if (!('spendingLimit' in value) || value['spendingLimit'] === undefined) return false;
    if (!('autoRecharge' in value) || value['autoRecharge'] === undefined) return false;
    if (!('currentPeriod' in value) || value['currentPeriod'] === undefined) return false;
    return true;
}

export function CreditBalanceFromJSON(json: any): CreditBalance {
    return CreditBalanceFromJSONTyped(json, false);
}

export function CreditBalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditBalance {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'balance': CreditBalanceInfoFromJSON(json['balance']),
        'pageLimit': PageLimitStatusFromJSON(json['pageLimit']),
        'spendingLimit': SpendingLimitStatusFromJSON(json['spendingLimit']),
        'autoRecharge': AutoRechargeSettingsFromJSON(json['autoRecharge']),
        'currentPeriod': PeriodChargesFromJSON(json['currentPeriod']),
        'usageHistory': json['usageHistory'] == null ? undefined : ((json['usageHistory'] as Array<any>).map(UsageHistoryItemFromJSON)),
    };
}

export function CreditBalanceToJSON(json: any): CreditBalance {
    return CreditBalanceToJSONTyped(json, false);
}

export function CreditBalanceToJSONTyped(value?: CreditBalance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'balance': CreditBalanceInfoToJSON(value['balance']),
        'pageLimit': PageLimitStatusToJSON(value['pageLimit']),
        'spendingLimit': SpendingLimitStatusToJSON(value['spendingLimit']),
        'autoRecharge': AutoRechargeSettingsToJSON(value['autoRecharge']),
        'currentPeriod': PeriodChargesToJSON(value['currentPeriod']),
        'usageHistory': value['usageHistory'] == null ? undefined : ((value['usageHistory'] as Array<any>).map(UsageHistoryItemToJSON)),
    };
}

