/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreditBalanceInfo
 */
export interface CreditBalanceInfo {
    /**
     * Project identifier
     * @type {string}
     * @memberof CreditBalanceInfo
     */
    projectId: string;
    /**
     * Total credits purchased
     * @type {number}
     * @memberof CreditBalanceInfo
     */
    creditsTotal: number;
    /**
     * Credits consumed
     * @type {number}
     * @memberof CreditBalanceInfo
     */
    creditsUsed: number;
    /**
     * Credits remaining
     * @type {number}
     * @memberof CreditBalanceInfo
     */
    creditsRemaining: number;
    /**
     * Last credit reset timestamp
     * @type {Date}
     * @memberof CreditBalanceInfo
     */
    lastResetAt?: Date;
}

/**
 * Check if a given object implements the CreditBalanceInfo interface.
 */
export function instanceOfCreditBalanceInfo(value: object): value is CreditBalanceInfo {
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('creditsTotal' in value) || value['creditsTotal'] === undefined) return false;
    if (!('creditsUsed' in value) || value['creditsUsed'] === undefined) return false;
    if (!('creditsRemaining' in value) || value['creditsRemaining'] === undefined) return false;
    return true;
}

export function CreditBalanceInfoFromJSON(json: any): CreditBalanceInfo {
    return CreditBalanceInfoFromJSONTyped(json, false);
}

export function CreditBalanceInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditBalanceInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'],
        'creditsTotal': json['creditsTotal'],
        'creditsUsed': json['creditsUsed'],
        'creditsRemaining': json['creditsRemaining'],
        'lastResetAt': json['lastResetAt'] == null ? undefined : (new Date(json['lastResetAt'])),
    };
}

export function CreditBalanceInfoToJSON(json: any): CreditBalanceInfo {
    return CreditBalanceInfoToJSONTyped(json, false);
}

export function CreditBalanceInfoToJSONTyped(value?: CreditBalanceInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projectId': value['projectId'],
        'creditsTotal': value['creditsTotal'],
        'creditsUsed': value['creditsUsed'],
        'creditsRemaining': value['creditsRemaining'],
        'lastResetAt': value['lastResetAt'] == null ? value['lastResetAt'] : value['lastResetAt'].toISOString(),
    };
}

