/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreditRatesExamplesCrawl100Pages
 */
export interface CreditRatesExamplesCrawl100Pages {
    /**
     * 
     * @type {number}
     * @memberof CreditRatesExamplesCrawl100Pages
     */
    credits?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditRatesExamplesCrawl100Pages
     */
    cost?: number;
}

/**
 * Check if a given object implements the CreditRatesExamplesCrawl100Pages interface.
 */
export function instanceOfCreditRatesExamplesCrawl100Pages(value: object): value is CreditRatesExamplesCrawl100Pages {
    return true;
}

export function CreditRatesExamplesCrawl100PagesFromJSON(json: any): CreditRatesExamplesCrawl100Pages {
    return CreditRatesExamplesCrawl100PagesFromJSONTyped(json, false);
}

export function CreditRatesExamplesCrawl100PagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditRatesExamplesCrawl100Pages {
    if (json == null) {
        return json;
    }
    return {
        
        'credits': json['credits'] == null ? undefined : json['credits'],
        'cost': json['cost'] == null ? undefined : json['cost'],
    };
}

export function CreditRatesExamplesCrawl100PagesToJSON(json: any): CreditRatesExamplesCrawl100Pages {
    return CreditRatesExamplesCrawl100PagesToJSONTyped(json, false);
}

export function CreditRatesExamplesCrawl100PagesToJSONTyped(value?: CreditRatesExamplesCrawl100Pages | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credits': value['credits'],
        'cost': value['cost'],
    };
}

