/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreditRatesRates
 */
export interface CreditRatesRates {
    /**
     * Credits per page crawled
     * @type {number}
     * @memberof CreditRatesRates
     */
    pageCrawl?: number;
    /**
     * Credits per link implemented
     * @type {number}
     * @memberof CreditRatesRates
     */
    linkImplementation?: number;
    /**
     * Credits per API query
     * @type {number}
     * @memberof CreditRatesRates
     */
    apiQuery?: number;
}

/**
 * Check if a given object implements the CreditRatesRates interface.
 */
export function instanceOfCreditRatesRates(value: object): value is CreditRatesRates {
    return true;
}

export function CreditRatesRatesFromJSON(json: any): CreditRatesRates {
    return CreditRatesRatesFromJSONTyped(json, false);
}

export function CreditRatesRatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditRatesRates {
    if (json == null) {
        return json;
    }
    return {
        
        'pageCrawl': json['pageCrawl'] == null ? undefined : json['pageCrawl'],
        'linkImplementation': json['linkImplementation'] == null ? undefined : json['linkImplementation'],
        'apiQuery': json['apiQuery'] == null ? undefined : json['apiQuery'],
    };
}

export function CreditRatesRatesToJSON(json: any): CreditRatesRates {
    return CreditRatesRatesToJSONTyped(json, false);
}

export function CreditRatesRatesToJSONTyped(value?: CreditRatesRates | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageCrawl': value['pageCrawl'],
        'linkImplementation': value['linkImplementation'],
        'apiQuery': value['apiQuery'],
    };
}

