/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteProject200Response
 */
export interface DeleteProject200Response {
    /**
     * 
     * @type {boolean}
     * @memberof DeleteProject200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DeleteProject200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the DeleteProject200Response interface.
 */
export function instanceOfDeleteProject200Response(value: object): value is DeleteProject200Response {
    return true;
}

export function DeleteProject200ResponseFromJSON(json: any): DeleteProject200Response {
    return DeleteProject200ResponseFromJSONTyped(json, false);
}

export function DeleteProject200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteProject200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function DeleteProject200ResponseToJSON(json: any): DeleteProject200Response {
    return DeleteProject200ResponseToJSONTyped(json, false);
}

export function DeleteProject200ResponseToJSONTyped(value?: DeleteProject200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
    };
}

