/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LinkOpportunity } from './LinkOpportunity';
import {
    LinkOpportunityFromJSON,
    LinkOpportunityFromJSONTyped,
    LinkOpportunityToJSON,
    LinkOpportunityToJSONTyped,
} from './LinkOpportunity';

/**
 * 
 * @export
 * @interface GenerateSuggestions200Response
 */
export interface GenerateSuggestions200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GenerateSuggestions200Response
     */
    success?: boolean;
    /**
     * Number of suggestions generated
     * @type {number}
     * @memberof GenerateSuggestions200Response
     */
    count?: number;
    /**
     * Top 10 opportunities preview
     * @type {Array<LinkOpportunity>}
     * @memberof GenerateSuggestions200Response
     */
    opportunities?: Array<LinkOpportunity>;
}

/**
 * Check if a given object implements the GenerateSuggestions200Response interface.
 */
export function instanceOfGenerateSuggestions200Response(value: object): value is GenerateSuggestions200Response {
    return true;
}

export function GenerateSuggestions200ResponseFromJSON(json: any): GenerateSuggestions200Response {
    return GenerateSuggestions200ResponseFromJSONTyped(json, false);
}

export function GenerateSuggestions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateSuggestions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'count': json['count'] == null ? undefined : json['count'],
        'opportunities': json['opportunities'] == null ? undefined : ((json['opportunities'] as Array<any>).map(LinkOpportunityFromJSON)),
    };
}

export function GenerateSuggestions200ResponseToJSON(json: any): GenerateSuggestions200Response {
    return GenerateSuggestions200ResponseToJSONTyped(json, false);
}

export function GenerateSuggestions200ResponseToJSONTyped(value?: GenerateSuggestions200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'count': value['count'],
        'opportunities': value['opportunities'] == null ? undefined : ((value['opportunities'] as Array<any>).map(LinkOpportunityToJSON)),
    };
}

