/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageChange } from './PageChange';
import {
    PageChangeFromJSON,
    PageChangeFromJSONTyped,
    PageChangeToJSON,
    PageChangeToJSONTyped,
} from './PageChange';
import type { GetPageChanges200ResponseSummary } from './GetPageChanges200ResponseSummary';
import {
    GetPageChanges200ResponseSummaryFromJSON,
    GetPageChanges200ResponseSummaryFromJSONTyped,
    GetPageChanges200ResponseSummaryToJSON,
    GetPageChanges200ResponseSummaryToJSONTyped,
} from './GetPageChanges200ResponseSummary';

/**
 * 
 * @export
 * @interface GetPageChanges200Response
 */
export interface GetPageChanges200Response {
    /**
     * 
     * @type {Array<PageChange>}
     * @memberof GetPageChanges200Response
     */
    changes?: Array<PageChange>;
    /**
     * 
     * @type {GetPageChanges200ResponseSummary}
     * @memberof GetPageChanges200Response
     */
    summary?: GetPageChanges200ResponseSummary;
}

/**
 * Check if a given object implements the GetPageChanges200Response interface.
 */
export function instanceOfGetPageChanges200Response(value: object): value is GetPageChanges200Response {
    return true;
}

export function GetPageChanges200ResponseFromJSON(json: any): GetPageChanges200Response {
    return GetPageChanges200ResponseFromJSONTyped(json, false);
}

export function GetPageChanges200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPageChanges200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'changes': json['changes'] == null ? undefined : ((json['changes'] as Array<any>).map(PageChangeFromJSON)),
        'summary': json['summary'] == null ? undefined : GetPageChanges200ResponseSummaryFromJSON(json['summary']),
    };
}

export function GetPageChanges200ResponseToJSON(json: any): GetPageChanges200Response {
    return GetPageChanges200ResponseToJSONTyped(json, false);
}

export function GetPageChanges200ResponseToJSONTyped(value?: GetPageChanges200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'changes': value['changes'] == null ? undefined : ((value['changes'] as Array<any>).map(PageChangeToJSON)),
        'summary': GetPageChanges200ResponseSummaryToJSON(value['summary']),
    };
}

