/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImplementationSummary
 */
export interface ImplementationSummary {
    /**
     * Total number of implementations
     * @type {number}
     * @memberof ImplementationSummary
     */
    total: number;
    /**
     * Number of successful implementations
     * @type {number}
     * @memberof ImplementationSummary
     */
    succeeded: number;
    /**
     * Number of failed implementations
     * @type {number}
     * @memberof ImplementationSummary
     */
    failed: number;
    /**
     * Total credits used
     * @type {number}
     * @memberof ImplementationSummary
     */
    creditsUsed: number;
}

/**
 * Check if a given object implements the ImplementationSummary interface.
 */
export function instanceOfImplementationSummary(value: object): value is ImplementationSummary {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('succeeded' in value) || value['succeeded'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    if (!('creditsUsed' in value) || value['creditsUsed'] === undefined) return false;
    return true;
}

export function ImplementationSummaryFromJSON(json: any): ImplementationSummary {
    return ImplementationSummaryFromJSONTyped(json, false);
}

export function ImplementationSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImplementationSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'succeeded': json['succeeded'],
        'failed': json['failed'],
        'creditsUsed': json['creditsUsed'],
    };
}

export function ImplementationSummaryToJSON(json: any): ImplementationSummary {
    return ImplementationSummaryToJSONTyped(json, false);
}

export function ImplementationSummaryToJSONTyped(value?: ImplementationSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'succeeded': value['succeeded'],
        'failed': value['failed'],
        'creditsUsed': value['creditsUsed'],
    };
}

