/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Suggestion } from './Suggestion';
import {
    SuggestionFromJSON,
    SuggestionFromJSONTyped,
    SuggestionToJSON,
    SuggestionToJSONTyped,
} from './Suggestion';
import type { Rollback } from './Rollback';
import {
    RollbackFromJSON,
    RollbackFromJSONTyped,
    RollbackToJSON,
    RollbackToJSONTyped,
} from './Rollback';

/**
 * 
 * @export
 * @interface Implementation
 */
export interface Implementation {
    /**
     * Unique implementation identifier
     * @type {string}
     * @memberof Implementation
     */
    id: string;
    /**
     * Implementation status
     * @type {string}
     * @memberof Implementation
     */
    status: ImplementationStatusEnum;
    /**
     * Platform used
     * @type {string}
     * @memberof Implementation
     */
    platform: ImplementationPlatformEnum;
    /**
     * Implementation method
     * @type {string}
     * @memberof Implementation
     */
    implementationMethod?: ImplementationImplementationMethodEnum;
    /**
     * Credits consumed
     * @type {number}
     * @memberof Implementation
     */
    creditsUsed: number;
    /**
     * Implementation start timestamp
     * @type {Date}
     * @memberof Implementation
     */
    createdAt: Date;
    /**
     * Implementation completion timestamp
     * @type {Date}
     * @memberof Implementation
     */
    completedAt?: Date;
    /**
     * Platform-specific metadata
     * @type {{ [key: string]: any; }}
     * @memberof Implementation
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {Suggestion}
     * @memberof Implementation
     */
    suggestion: Suggestion;
    /**
     * Rollback history
     * @type {Array<Rollback>}
     * @memberof Implementation
     */
    rollbacks?: Array<Rollback>;
}


/**
 * @export
 */
export const ImplementationStatusEnum = {
    Pending: 'pending',
    InProgress: 'in_progress',
    Success: 'success',
    Failed: 'failed',
    RolledBack: 'rolled_back'
} as const;
export type ImplementationStatusEnum = typeof ImplementationStatusEnum[keyof typeof ImplementationStatusEnum];

/**
 * @export
 */
export const ImplementationPlatformEnum = {
    Custom: 'custom'
} as const;
export type ImplementationPlatformEnum = typeof ImplementationPlatformEnum[keyof typeof ImplementationPlatformEnum];

/**
 * @export
 */
export const ImplementationImplementationMethodEnum = {
    Api: 'api',
    Manual: 'manual'
} as const;
export type ImplementationImplementationMethodEnum = typeof ImplementationImplementationMethodEnum[keyof typeof ImplementationImplementationMethodEnum];


/**
 * Check if a given object implements the Implementation interface.
 */
export function instanceOfImplementation(value: object): value is Implementation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('creditsUsed' in value) || value['creditsUsed'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('suggestion' in value) || value['suggestion'] === undefined) return false;
    return true;
}

export function ImplementationFromJSON(json: any): Implementation {
    return ImplementationFromJSONTyped(json, false);
}

export function ImplementationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Implementation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'platform': json['platform'],
        'implementationMethod': json['implementationMethod'] == null ? undefined : json['implementationMethod'],
        'creditsUsed': json['creditsUsed'],
        'createdAt': (new Date(json['createdAt'])),
        'completedAt': json['completedAt'] == null ? undefined : (new Date(json['completedAt'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'suggestion': SuggestionFromJSON(json['suggestion']),
        'rollbacks': json['rollbacks'] == null ? undefined : ((json['rollbacks'] as Array<any>).map(RollbackFromJSON)),
    };
}

export function ImplementationToJSON(json: any): Implementation {
    return ImplementationToJSONTyped(json, false);
}

export function ImplementationToJSONTyped(value?: Implementation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'platform': value['platform'],
        'implementationMethod': value['implementationMethod'],
        'creditsUsed': value['creditsUsed'],
        'createdAt': value['createdAt'].toISOString(),
        'completedAt': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'metadata': value['metadata'],
        'suggestion': SuggestionToJSON(value['suggestion']),
        'rollbacks': value['rollbacks'] == null ? undefined : ((value['rollbacks'] as Array<any>).map(RollbackToJSON)),
    };
}

