/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StepByStepInstructions } from './StepByStepInstructions';
import {
    StepByStepInstructionsFromJSON,
    StepByStepInstructionsFromJSONTyped,
    StepByStepInstructionsToJSON,
    StepByStepInstructionsToJSONTyped,
} from './StepByStepInstructions';

/**
 * 
 * @export
 * @interface ImplementationInstructions
 */
export interface ImplementationInstructions {
    /**
     * Suggestion identifier
     * @type {string}
     * @memberof ImplementationInstructions
     */
    suggestionId: string;
    /**
     * URL of the page to modify
     * @type {string}
     * @memberof ImplementationInstructions
     */
    pageUrl: string;
    /**
     * Text to turn into a link
     * @type {string}
     * @memberof ImplementationInstructions
     */
    anchorText: string;
    /**
     * URL to link to
     * @type {string}
     * @memberof ImplementationInstructions
     */
    targetUrl: string;
    /**
     * Context where the link should be placed
     * @type {string}
     * @memberof ImplementationInstructions
     */
    context: string;
    /**
     * 
     * @type {StepByStepInstructions}
     * @memberof ImplementationInstructions
     */
    instructions: StepByStepInstructions;
}

/**
 * Check if a given object implements the ImplementationInstructions interface.
 */
export function instanceOfImplementationInstructions(value: object): value is ImplementationInstructions {
    if (!('suggestionId' in value) || value['suggestionId'] === undefined) return false;
    if (!('pageUrl' in value) || value['pageUrl'] === undefined) return false;
    if (!('anchorText' in value) || value['anchorText'] === undefined) return false;
    if (!('targetUrl' in value) || value['targetUrl'] === undefined) return false;
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('instructions' in value) || value['instructions'] === undefined) return false;
    return true;
}

export function ImplementationInstructionsFromJSON(json: any): ImplementationInstructions {
    return ImplementationInstructionsFromJSONTyped(json, false);
}

export function ImplementationInstructionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImplementationInstructions {
    if (json == null) {
        return json;
    }
    return {
        
        'suggestionId': json['suggestionId'],
        'pageUrl': json['pageUrl'],
        'anchorText': json['anchorText'],
        'targetUrl': json['targetUrl'],
        'context': json['context'],
        'instructions': StepByStepInstructionsFromJSON(json['instructions']),
    };
}

export function ImplementationInstructionsToJSON(json: any): ImplementationInstructions {
    return ImplementationInstructionsToJSONTyped(json, false);
}

export function ImplementationInstructionsToJSONTyped(value?: ImplementationInstructions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'suggestionId': value['suggestionId'],
        'pageUrl': value['pageUrl'],
        'anchorText': value['anchorText'],
        'targetUrl': value['targetUrl'],
        'context': value['context'],
        'instructions': StepByStepInstructionsToJSON(value['instructions']),
    };
}

