/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageInfo } from './PageInfo';
import {
    PageInfoFromJSON,
    PageInfoFromJSONTyped,
    PageInfoToJSON,
    PageInfoToJSONTyped,
} from './PageInfo';

/**
 * 
 * @export
 * @interface LinkOpportunity
 */
export interface LinkOpportunity {
    /**
     * AI-calculated relevance score (0-1)
     * @type {number}
     * @memberof LinkOpportunity
     */
    relevanceScore: number;
    /**
     * Suggested anchor text
     * @type {string}
     * @memberof LinkOpportunity
     */
    anchorText: string;
    /**
     * Context where the link should be placed
     * @type {string}
     * @memberof LinkOpportunity
     */
    context?: string;
    /**
     * 
     * @type {PageInfo}
     * @memberof LinkOpportunity
     */
    sourcePage: PageInfo;
    /**
     * 
     * @type {PageInfo}
     * @memberof LinkOpportunity
     */
    targetPage: PageInfo;
    /**
     * AI reasoning for the suggestion
     * @type {string}
     * @memberof LinkOpportunity
     */
    reasoning?: string;
}

/**
 * Check if a given object implements the LinkOpportunity interface.
 */
export function instanceOfLinkOpportunity(value: object): value is LinkOpportunity {
    if (!('relevanceScore' in value) || value['relevanceScore'] === undefined) return false;
    if (!('anchorText' in value) || value['anchorText'] === undefined) return false;
    if (!('sourcePage' in value) || value['sourcePage'] === undefined) return false;
    if (!('targetPage' in value) || value['targetPage'] === undefined) return false;
    return true;
}

export function LinkOpportunityFromJSON(json: any): LinkOpportunity {
    return LinkOpportunityFromJSONTyped(json, false);
}

export function LinkOpportunityFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkOpportunity {
    if (json == null) {
        return json;
    }
    return {
        
        'relevanceScore': json['relevanceScore'],
        'anchorText': json['anchorText'],
        'context': json['context'] == null ? undefined : json['context'],
        'sourcePage': PageInfoFromJSON(json['sourcePage']),
        'targetPage': PageInfoFromJSON(json['targetPage']),
        'reasoning': json['reasoning'] == null ? undefined : json['reasoning'],
    };
}

export function LinkOpportunityToJSON(json: any): LinkOpportunity {
    return LinkOpportunityToJSONTyped(json, false);
}

export function LinkOpportunityToJSONTyped(value?: LinkOpportunity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'relevanceScore': value['relevanceScore'],
        'anchorText': value['anchorText'],
        'context': value['context'],
        'sourcePage': PageInfoToJSON(value['sourcePage']),
        'targetPage': PageInfoToJSON(value['targetPage']),
        'reasoning': value['reasoning'],
    };
}

