/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PagePricingPagePacksInner
 */
export interface PagePricingPagePacksInner {
    /**
     * 
     * @type {string}
     * @memberof PagePricingPagePacksInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PagePricingPagePacksInner
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof PagePricingPagePacksInner
     */
    pages?: number;
    /**
     * 
     * @type {number}
     * @memberof PagePricingPagePacksInner
     */
    price?: number;
}

/**
 * Check if a given object implements the PagePricingPagePacksInner interface.
 */
export function instanceOfPagePricingPagePacksInner(value: object): value is PagePricingPagePacksInner {
    return true;
}

export function PagePricingPagePacksInnerFromJSON(json: any): PagePricingPagePacksInner {
    return PagePricingPagePacksInnerFromJSONTyped(json, false);
}

export function PagePricingPagePacksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagePricingPagePacksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'pages': json['pages'] == null ? undefined : json['pages'],
        'price': json['price'] == null ? undefined : json['price'],
    };
}

export function PagePricingPagePacksInnerToJSON(json: any): PagePricingPagePacksInner {
    return PagePricingPagePacksInnerToJSONTyped(json, false);
}

export function PagePricingPagePacksInnerToJSONTyped(value?: PagePricingPagePacksInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'pages': value['pages'],
        'price': value['price'],
    };
}

