/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageChangePage } from './PageChangePage';
import {
    PageChangePageFromJSON,
    PageChangePageFromJSONTyped,
    PageChangePageToJSON,
    PageChangePageToJSONTyped,
} from './PageChangePage';

/**
 * 
 * @export
 * @interface PageChange
 */
export interface PageChange {
    /**
     * Change identifier
     * @type {string}
     * @memberof PageChange
     */
    id: string;
    /**
     * Page identifier
     * @type {string}
     * @memberof PageChange
     */
    pageId: string;
    /**
     * Project identifier
     * @type {string}
     * @memberof PageChange
     */
    projectId: string;
    /**
     * Change status
     * @type {string}
     * @memberof PageChange
     */
    changeStatus: PageChangeChangeStatusEnum;
    /**
     * Page visibility
     * @type {string}
     * @memberof PageChange
     */
    visibility: PageChangeVisibilityEnum;
    /**
     * Previous scrape timestamp
     * @type {Date}
     * @memberof PageChange
     */
    previousScrapeAt?: Date | null;
    /**
     * Current scrape timestamp
     * @type {Date}
     * @memberof PageChange
     */
    currentScrapeAt: Date;
    /**
     * 
     * @type {PageChangePage}
     * @memberof PageChange
     */
    page?: PageChangePage;
}


/**
 * @export
 */
export const PageChangeChangeStatusEnum = {
    New: 'new',
    Same: 'same',
    Changed: 'changed',
    Removed: 'removed'
} as const;
export type PageChangeChangeStatusEnum = typeof PageChangeChangeStatusEnum[keyof typeof PageChangeChangeStatusEnum];

/**
 * @export
 */
export const PageChangeVisibilityEnum = {
    Visible: 'visible',
    Hidden: 'hidden',
    Error: 'error'
} as const;
export type PageChangeVisibilityEnum = typeof PageChangeVisibilityEnum[keyof typeof PageChangeVisibilityEnum];


/**
 * Check if a given object implements the PageChange interface.
 */
export function instanceOfPageChange(value: object): value is PageChange {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('pageId' in value) || value['pageId'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('changeStatus' in value) || value['changeStatus'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    if (!('currentScrapeAt' in value) || value['currentScrapeAt'] === undefined) return false;
    return true;
}

export function PageChangeFromJSON(json: any): PageChange {
    return PageChangeFromJSONTyped(json, false);
}

export function PageChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageChange {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'pageId': json['pageId'],
        'projectId': json['projectId'],
        'changeStatus': json['changeStatus'],
        'visibility': json['visibility'],
        'previousScrapeAt': json['previousScrapeAt'] == null ? undefined : (new Date(json['previousScrapeAt'])),
        'currentScrapeAt': (new Date(json['currentScrapeAt'])),
        'page': json['page'] == null ? undefined : PageChangePageFromJSON(json['page']),
    };
}

export function PageChangeToJSON(json: any): PageChange {
    return PageChangeToJSONTyped(json, false);
}

export function PageChangeToJSONTyped(value?: PageChange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'pageId': value['pageId'],
        'projectId': value['projectId'],
        'changeStatus': value['changeStatus'],
        'visibility': value['visibility'],
        'previousScrapeAt': value['previousScrapeAt'] == null ? value['previousScrapeAt'] : value['previousScrapeAt'].toISOString(),
        'currentScrapeAt': value['currentScrapeAt'].toISOString(),
        'page': PageChangePageToJSON(value['page']),
    };
}

