/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PeriodCharges
 */
export interface PeriodCharges {
    /**
     * Period start date
     * @type {Date}
     * @memberof PeriodCharges
     */
    startDate: Date;
    /**
     * Period end date
     * @type {Date}
     * @memberof PeriodCharges
     */
    endDate: Date;
    /**
     * Total charges for the period
     * @type {number}
     * @memberof PeriodCharges
     */
    totalCharges: number;
}

/**
 * Check if a given object implements the PeriodCharges interface.
 */
export function instanceOfPeriodCharges(value: object): value is PeriodCharges {
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('totalCharges' in value) || value['totalCharges'] === undefined) return false;
    return true;
}

export function PeriodChargesFromJSON(json: any): PeriodCharges {
    return PeriodChargesFromJSONTyped(json, false);
}

export function PeriodChargesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PeriodCharges {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
        'totalCharges': json['totalCharges'],
    };
}

export function PeriodChargesToJSON(json: any): PeriodCharges {
    return PeriodChargesToJSONTyped(json, false);
}

export function PeriodChargesToJSONTyped(value?: PeriodCharges | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startDate': value['startDate'].toISOString(),
        'endDate': value['endDate'].toISOString(),
        'totalCharges': value['totalCharges'],
    };
}

