/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectAnalyticsSuggestionStats } from './ProjectAnalyticsSuggestionStats';
import {
    ProjectAnalyticsSuggestionStatsFromJSON,
    ProjectAnalyticsSuggestionStatsFromJSONTyped,
    ProjectAnalyticsSuggestionStatsToJSON,
    ProjectAnalyticsSuggestionStatsToJSONTyped,
} from './ProjectAnalyticsSuggestionStats';
import type { Suggestion } from './Suggestion';
import {
    SuggestionFromJSON,
    SuggestionFromJSONTyped,
    SuggestionToJSON,
    SuggestionToJSONTyped,
} from './Suggestion';
import type { ProjectAnalyticsImplementationStats } from './ProjectAnalyticsImplementationStats';
import {
    ProjectAnalyticsImplementationStatsFromJSON,
    ProjectAnalyticsImplementationStatsFromJSONTyped,
    ProjectAnalyticsImplementationStatsToJSON,
    ProjectAnalyticsImplementationStatsToJSONTyped,
} from './ProjectAnalyticsImplementationStats';
import type { ProjectAnalyticsSyncStats } from './ProjectAnalyticsSyncStats';
import {
    ProjectAnalyticsSyncStatsFromJSON,
    ProjectAnalyticsSyncStatsFromJSONTyped,
    ProjectAnalyticsSyncStatsToJSON,
    ProjectAnalyticsSyncStatsToJSONTyped,
} from './ProjectAnalyticsSyncStats';
import type { ProjectAnalyticsContentStats } from './ProjectAnalyticsContentStats';
import {
    ProjectAnalyticsContentStatsFromJSON,
    ProjectAnalyticsContentStatsFromJSONTyped,
    ProjectAnalyticsContentStatsToJSON,
    ProjectAnalyticsContentStatsToJSONTyped,
} from './ProjectAnalyticsContentStats';
import type { Implementation } from './Implementation';
import {
    ImplementationFromJSON,
    ImplementationFromJSONTyped,
    ImplementationToJSON,
    ImplementationToJSONTyped,
} from './Implementation';

/**
 * 
 * @export
 * @interface ProjectAnalytics
 */
export interface ProjectAnalytics {
    /**
     * 
     * @type {ProjectAnalyticsImplementationStats}
     * @memberof ProjectAnalytics
     */
    implementationStats: ProjectAnalyticsImplementationStats;
    /**
     * 
     * @type {ProjectAnalyticsSuggestionStats}
     * @memberof ProjectAnalytics
     */
    suggestionStats: ProjectAnalyticsSuggestionStats;
    /**
     * 
     * @type {ProjectAnalyticsSyncStats}
     * @memberof ProjectAnalytics
     */
    syncStats: ProjectAnalyticsSyncStats;
    /**
     * 
     * @type {ProjectAnalyticsContentStats}
     * @memberof ProjectAnalytics
     */
    contentStats: ProjectAnalyticsContentStats;
    /**
     * 
     * @type {Array<object>}
     * @memberof ProjectAnalytics
     */
    topSourcePages?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof ProjectAnalytics
     */
    topTargetPages?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof ProjectAnalytics
     */
    orphanedPages?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof ProjectAnalytics
     */
    highPerformingPages?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof ProjectAnalytics
     */
    mostSuggestedPages?: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof ProjectAnalytics
     */
    mostLinkedToPages?: Array<object>;
    /**
     * 
     * @type {Array<Implementation>}
     * @memberof ProjectAnalytics
     */
    recentImplementations?: Array<Implementation>;
    /**
     * 
     * @type {Array<Suggestion>}
     * @memberof ProjectAnalytics
     */
    recentSuggestions?: Array<Suggestion>;
    /**
     * 
     * @type {Array<object>}
     * @memberof ProjectAnalytics
     */
    recentSyncs?: Array<object>;
}

/**
 * Check if a given object implements the ProjectAnalytics interface.
 */
export function instanceOfProjectAnalytics(value: object): value is ProjectAnalytics {
    if (!('implementationStats' in value) || value['implementationStats'] === undefined) return false;
    if (!('suggestionStats' in value) || value['suggestionStats'] === undefined) return false;
    if (!('syncStats' in value) || value['syncStats'] === undefined) return false;
    if (!('contentStats' in value) || value['contentStats'] === undefined) return false;
    return true;
}

export function ProjectAnalyticsFromJSON(json: any): ProjectAnalytics {
    return ProjectAnalyticsFromJSONTyped(json, false);
}

export function ProjectAnalyticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectAnalytics {
    if (json == null) {
        return json;
    }
    return {
        
        'implementationStats': ProjectAnalyticsImplementationStatsFromJSON(json['implementationStats']),
        'suggestionStats': ProjectAnalyticsSuggestionStatsFromJSON(json['suggestionStats']),
        'syncStats': ProjectAnalyticsSyncStatsFromJSON(json['syncStats']),
        'contentStats': ProjectAnalyticsContentStatsFromJSON(json['contentStats']),
        'topSourcePages': json['topSourcePages'] == null ? undefined : json['topSourcePages'],
        'topTargetPages': json['topTargetPages'] == null ? undefined : json['topTargetPages'],
        'orphanedPages': json['orphanedPages'] == null ? undefined : json['orphanedPages'],
        'highPerformingPages': json['highPerformingPages'] == null ? undefined : json['highPerformingPages'],
        'mostSuggestedPages': json['mostSuggestedPages'] == null ? undefined : json['mostSuggestedPages'],
        'mostLinkedToPages': json['mostLinkedToPages'] == null ? undefined : json['mostLinkedToPages'],
        'recentImplementations': json['recentImplementations'] == null ? undefined : ((json['recentImplementations'] as Array<any>).map(ImplementationFromJSON)),
        'recentSuggestions': json['recentSuggestions'] == null ? undefined : ((json['recentSuggestions'] as Array<any>).map(SuggestionFromJSON)),
        'recentSyncs': json['recentSyncs'] == null ? undefined : json['recentSyncs'],
    };
}

export function ProjectAnalyticsToJSON(json: any): ProjectAnalytics {
    return ProjectAnalyticsToJSONTyped(json, false);
}

export function ProjectAnalyticsToJSONTyped(value?: ProjectAnalytics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'implementationStats': ProjectAnalyticsImplementationStatsToJSON(value['implementationStats']),
        'suggestionStats': ProjectAnalyticsSuggestionStatsToJSON(value['suggestionStats']),
        'syncStats': ProjectAnalyticsSyncStatsToJSON(value['syncStats']),
        'contentStats': ProjectAnalyticsContentStatsToJSON(value['contentStats']),
        'topSourcePages': value['topSourcePages'],
        'topTargetPages': value['topTargetPages'],
        'orphanedPages': value['orphanedPages'],
        'highPerformingPages': value['highPerformingPages'],
        'mostSuggestedPages': value['mostSuggestedPages'],
        'mostLinkedToPages': value['mostLinkedToPages'],
        'recentImplementations': value['recentImplementations'] == null ? undefined : ((value['recentImplementations'] as Array<any>).map(ImplementationToJSON)),
        'recentSuggestions': value['recentSuggestions'] == null ? undefined : ((value['recentSuggestions'] as Array<any>).map(SuggestionToJSON)),
        'recentSyncs': value['recentSyncs'],
    };
}

