/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectAnalyticsContentStats
 */
export interface ProjectAnalyticsContentStats {
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsContentStats
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsContentStats
     */
    avgWordCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsContentStats
     */
    totalWords?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsContentStats
     */
    pagesWithLinks?: number;
    /**
     * 
     * @type {object}
     * @memberof ProjectAnalyticsContentStats
     */
    wordCountDistribution?: object;
    /**
     * 
     * @type {object}
     * @memberof ProjectAnalyticsContentStats
     */
    internalLinkDistribution?: object;
}

/**
 * Check if a given object implements the ProjectAnalyticsContentStats interface.
 */
export function instanceOfProjectAnalyticsContentStats(value: object): value is ProjectAnalyticsContentStats {
    return true;
}

export function ProjectAnalyticsContentStatsFromJSON(json: any): ProjectAnalyticsContentStats {
    return ProjectAnalyticsContentStatsFromJSONTyped(json, false);
}

export function ProjectAnalyticsContentStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectAnalyticsContentStats {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'avgWordCount': json['avgWordCount'] == null ? undefined : json['avgWordCount'],
        'totalWords': json['totalWords'] == null ? undefined : json['totalWords'],
        'pagesWithLinks': json['pagesWithLinks'] == null ? undefined : json['pagesWithLinks'],
        'wordCountDistribution': json['wordCountDistribution'] == null ? undefined : json['wordCountDistribution'],
        'internalLinkDistribution': json['internalLinkDistribution'] == null ? undefined : json['internalLinkDistribution'],
    };
}

export function ProjectAnalyticsContentStatsToJSON(json: any): ProjectAnalyticsContentStats {
    return ProjectAnalyticsContentStatsToJSONTyped(json, false);
}

export function ProjectAnalyticsContentStatsToJSONTyped(value?: ProjectAnalyticsContentStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalPages': value['totalPages'],
        'avgWordCount': value['avgWordCount'],
        'totalWords': value['totalWords'],
        'pagesWithLinks': value['pagesWithLinks'],
        'wordCountDistribution': value['wordCountDistribution'],
        'internalLinkDistribution': value['internalLinkDistribution'],
    };
}

