/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectAnalyticsSuggestionStats
 */
export interface ProjectAnalyticsSuggestionStats {
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsSuggestionStats
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsSuggestionStats
     */
    pending?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsSuggestionStats
     */
    approved?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsSuggestionStats
     */
    rejected?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsSuggestionStats
     */
    implemented?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsSuggestionStats
     */
    acceptanceRate?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsSuggestionStats
     */
    implementationRate?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectAnalyticsSuggestionStats
     */
    avgRelevanceScore?: number;
    /**
     * 
     * @type {object}
     * @memberof ProjectAnalyticsSuggestionStats
     */
    relevanceScoreDistribution?: object;
}

/**
 * Check if a given object implements the ProjectAnalyticsSuggestionStats interface.
 */
export function instanceOfProjectAnalyticsSuggestionStats(value: object): value is ProjectAnalyticsSuggestionStats {
    return true;
}

export function ProjectAnalyticsSuggestionStatsFromJSON(json: any): ProjectAnalyticsSuggestionStats {
    return ProjectAnalyticsSuggestionStatsFromJSONTyped(json, false);
}

export function ProjectAnalyticsSuggestionStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectAnalyticsSuggestionStats {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'pending': json['pending'] == null ? undefined : json['pending'],
        'approved': json['approved'] == null ? undefined : json['approved'],
        'rejected': json['rejected'] == null ? undefined : json['rejected'],
        'implemented': json['implemented'] == null ? undefined : json['implemented'],
        'acceptanceRate': json['acceptanceRate'] == null ? undefined : json['acceptanceRate'],
        'implementationRate': json['implementationRate'] == null ? undefined : json['implementationRate'],
        'avgRelevanceScore': json['avgRelevanceScore'] == null ? undefined : json['avgRelevanceScore'],
        'relevanceScoreDistribution': json['relevanceScoreDistribution'] == null ? undefined : json['relevanceScoreDistribution'],
    };
}

export function ProjectAnalyticsSuggestionStatsToJSON(json: any): ProjectAnalyticsSuggestionStats {
    return ProjectAnalyticsSuggestionStatsToJSONTyped(json, false);
}

export function ProjectAnalyticsSuggestionStatsToJSONTyped(value?: ProjectAnalyticsSuggestionStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'pending': value['pending'],
        'approved': value['approved'],
        'rejected': value['rejected'],
        'implemented': value['implemented'],
        'acceptanceRate': value['acceptanceRate'],
        'implementationRate': value['implementationRate'],
        'avgRelevanceScore': value['avgRelevanceScore'],
        'relevanceScoreDistribution': value['relevanceScoreDistribution'],
    };
}

