/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomCredentials } from './CustomCredentials';
import {
    CustomCredentialsFromJSON,
    CustomCredentialsFromJSONTyped,
    CustomCredentialsToJSON,
    CustomCredentialsToJSONTyped,
} from './CustomCredentials';

/**
 * 
 * @export
 * @interface RollbackImplementationRequest
 */
export interface RollbackImplementationRequest {
    /**
     * Reason for rollback
     * @type {string}
     * @memberof RollbackImplementationRequest
     */
    reason: string;
    /**
     * 
     * @type {CustomCredentials}
     * @memberof RollbackImplementationRequest
     */
    credentials?: CustomCredentials;
}

/**
 * Check if a given object implements the RollbackImplementationRequest interface.
 */
export function instanceOfRollbackImplementationRequest(value: object): value is RollbackImplementationRequest {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function RollbackImplementationRequestFromJSON(json: any): RollbackImplementationRequest {
    return RollbackImplementationRequestFromJSONTyped(json, false);
}

export function RollbackImplementationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RollbackImplementationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'],
        'credentials': json['credentials'] == null ? undefined : CustomCredentialsFromJSON(json['credentials']),
    };
}

export function RollbackImplementationRequestToJSON(json: any): RollbackImplementationRequest {
    return RollbackImplementationRequestToJSONTyped(json, false);
}

export function RollbackImplementationRequestToJSONTyped(value?: RollbackImplementationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
        'credentials': CustomCredentialsToJSON(value['credentials']),
    };
}

