/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Rollback
 */
export interface Rollback {
    /**
     * Unique rollback identifier
     * @type {string}
     * @memberof Rollback
     */
    id: string;
    /**
     * Reason for rollback
     * @type {string}
     * @memberof Rollback
     */
    reason: string;
    /**
     * Rollback timestamp
     * @type {Date}
     * @memberof Rollback
     */
    createdAt: Date;
    /**
     * Credits refunded
     * @type {number}
     * @memberof Rollback
     */
    creditsRefunded?: number;
}

/**
 * Check if a given object implements the Rollback interface.
 */
export function instanceOfRollback(value: object): value is Rollback {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function RollbackFromJSON(json: any): Rollback {
    return RollbackFromJSONTyped(json, false);
}

export function RollbackFromJSONTyped(json: any, ignoreDiscriminator: boolean): Rollback {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'reason': json['reason'],
        'createdAt': (new Date(json['createdAt'])),
        'creditsRefunded': json['creditsRefunded'] == null ? undefined : json['creditsRefunded'],
    };
}

export function RollbackToJSON(json: any): Rollback {
    return RollbackToJSONTyped(json, false);
}

export function RollbackToJSONTyped(value?: Rollback | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'reason': value['reason'],
        'createdAt': value['createdAt'].toISOString(),
        'creditsRefunded': value['creditsRefunded'],
    };
}

