/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpendingLimitStatus
 */
export interface SpendingLimitStatus {
    /**
     * Whether spending limit is enabled
     * @type {boolean}
     * @memberof SpendingLimitStatus
     */
    enabled: boolean;
    /**
     * Spending limit
     * @type {number}
     * @memberof SpendingLimitStatus
     */
    limit: number;
    /**
     * Amount used
     * @type {number}
     * @memberof SpendingLimitStatus
     */
    used: number;
    /**
     * Amount remaining
     * @type {number}
     * @memberof SpendingLimitStatus
     */
    remaining: number;
}

/**
 * Check if a given object implements the SpendingLimitStatus interface.
 */
export function instanceOfSpendingLimitStatus(value: object): value is SpendingLimitStatus {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('used' in value) || value['used'] === undefined) return false;
    if (!('remaining' in value) || value['remaining'] === undefined) return false;
    return true;
}

export function SpendingLimitStatusFromJSON(json: any): SpendingLimitStatus {
    return SpendingLimitStatusFromJSONTyped(json, false);
}

export function SpendingLimitStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpendingLimitStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'limit': json['limit'],
        'used': json['used'],
        'remaining': json['remaining'],
    };
}

export function SpendingLimitStatusToJSON(json: any): SpendingLimitStatus {
    return SpendingLimitStatusToJSONTyped(json, false);
}

export function SpendingLimitStatusToJSONTyped(value?: SpendingLimitStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'limit': value['limit'],
        'used': value['used'],
        'remaining': value['remaining'],
    };
}

