/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StepByStepInstructions
 */
export interface StepByStepInstructions {
    /**
     * Step-by-step instructions
     * @type {Array<string>}
     * @memberof StepByStepInstructions
     */
    steps: Array<string>;
    /**
     * HTML example of the implementation
     * @type {string}
     * @memberof StepByStepInstructions
     */
    htmlExample: string;
}

/**
 * Check if a given object implements the StepByStepInstructions interface.
 */
export function instanceOfStepByStepInstructions(value: object): value is StepByStepInstructions {
    if (!('steps' in value) || value['steps'] === undefined) return false;
    if (!('htmlExample' in value) || value['htmlExample'] === undefined) return false;
    return true;
}

export function StepByStepInstructionsFromJSON(json: any): StepByStepInstructions {
    return StepByStepInstructionsFromJSONTyped(json, false);
}

export function StepByStepInstructionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepByStepInstructions {
    if (json == null) {
        return json;
    }
    return {
        
        'steps': json['steps'],
        'htmlExample': json['htmlExample'],
    };
}

export function StepByStepInstructionsToJSON(json: any): StepByStepInstructions {
    return StepByStepInstructionsToJSONTyped(json, false);
}

export function StepByStepInstructionsToJSONTyped(value?: StepByStepInstructions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'steps': value['steps'],
        'htmlExample': value['htmlExample'],
    };
}

