/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageInfo } from './PageInfo';
import {
    PageInfoFromJSON,
    PageInfoFromJSONTyped,
    PageInfoToJSON,
    PageInfoToJSONTyped,
} from './PageInfo';

/**
 * 
 * @export
 * @interface Suggestion
 */
export interface Suggestion {
    /**
     * Unique suggestion identifier
     * @type {string}
     * @memberof Suggestion
     */
    id: string;
    /**
     * Project identifier
     * @type {string}
     * @memberof Suggestion
     */
    projectId: string;
    /**
     * Suggestion status
     * @type {string}
     * @memberof Suggestion
     */
    status: SuggestionStatusEnum;
    /**
     * AI-calculated relevance score (0-1)
     * @type {number}
     * @memberof Suggestion
     */
    relevanceScore: number;
    /**
     * Suggested anchor text
     * @type {string}
     * @memberof Suggestion
     */
    anchorText: string;
    /**
     * Context where the link should be placed
     * @type {string}
     * @memberof Suggestion
     */
    context?: string;
    /**
     * 
     * @type {PageInfo}
     * @memberof Suggestion
     */
    sourcePage: PageInfo;
    /**
     * 
     * @type {PageInfo}
     * @memberof Suggestion
     */
    targetPage: PageInfo;
    /**
     * AI reasoning for the suggestion
     * @type {string}
     * @memberof Suggestion
     */
    reasoning?: string;
    /**
     * Suggestion creation timestamp
     * @type {Date}
     * @memberof Suggestion
     */
    createdAt: Date;
    /**
     * Last update timestamp
     * @type {Date}
     * @memberof Suggestion
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const SuggestionStatusEnum = {
    Pending: 'pending',
    Approved: 'approved',
    Rejected: 'rejected',
    Implemented: 'implemented'
} as const;
export type SuggestionStatusEnum = typeof SuggestionStatusEnum[keyof typeof SuggestionStatusEnum];


/**
 * Check if a given object implements the Suggestion interface.
 */
export function instanceOfSuggestion(value: object): value is Suggestion {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('relevanceScore' in value) || value['relevanceScore'] === undefined) return false;
    if (!('anchorText' in value) || value['anchorText'] === undefined) return false;
    if (!('sourcePage' in value) || value['sourcePage'] === undefined) return false;
    if (!('targetPage' in value) || value['targetPage'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function SuggestionFromJSON(json: any): Suggestion {
    return SuggestionFromJSONTyped(json, false);
}

export function SuggestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Suggestion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'projectId': json['projectId'],
        'status': json['status'],
        'relevanceScore': json['relevanceScore'],
        'anchorText': json['anchorText'],
        'context': json['context'] == null ? undefined : json['context'],
        'sourcePage': PageInfoFromJSON(json['sourcePage']),
        'targetPage': PageInfoFromJSON(json['targetPage']),
        'reasoning': json['reasoning'] == null ? undefined : json['reasoning'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function SuggestionToJSON(json: any): Suggestion {
    return SuggestionToJSONTyped(json, false);
}

export function SuggestionToJSONTyped(value?: Suggestion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'projectId': value['projectId'],
        'status': value['status'],
        'relevanceScore': value['relevanceScore'],
        'anchorText': value['anchorText'],
        'context': value['context'],
        'sourcePage': PageInfoToJSON(value['sourcePage']),
        'targetPage': PageInfoToJSON(value['targetPage']),
        'reasoning': value['reasoning'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

