/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateApiKeyRequest
 */
export interface UpdateApiKeyRequest {
    /**
     * New name for the API key
     * @type {string}
     * @memberof UpdateApiKeyRequest
     */
    name?: string;
    /**
     * Activate or deactivate the key
     * @type {boolean}
     * @memberof UpdateApiKeyRequest
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the UpdateApiKeyRequest interface.
 */
export function instanceOfUpdateApiKeyRequest(value: object): value is UpdateApiKeyRequest {
    return true;
}

export function UpdateApiKeyRequestFromJSON(json: any): UpdateApiKeyRequest {
    return UpdateApiKeyRequestFromJSONTyped(json, false);
}

export function UpdateApiKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateApiKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function UpdateApiKeyRequestToJSON(json: any): UpdateApiKeyRequest {
    return UpdateApiKeyRequestToJSONTyped(json, false);
}

export function UpdateApiKeyRequestToJSONTyped(value?: UpdateApiKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'isActive': value['isActive'],
    };
}

