/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsageHistoryItem
 */
export interface UsageHistoryItem {
    /**
     * Usage item identifier
     * @type {string}
     * @memberof UsageHistoryItem
     */
    id: string;
    /**
     * Action performed
     * @type {string}
     * @memberof UsageHistoryItem
     */
    action: string;
    /**
     * Credits used
     * @type {number}
     * @memberof UsageHistoryItem
     */
    creditsUsed: number;
    /**
     * Usage timestamp
     * @type {Date}
     * @memberof UsageHistoryItem
     */
    createdAt: Date;
    /**
     * Additional metadata
     * @type {{ [key: string]: any; }}
     * @memberof UsageHistoryItem
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the UsageHistoryItem interface.
 */
export function instanceOfUsageHistoryItem(value: object): value is UsageHistoryItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('creditsUsed' in value) || value['creditsUsed'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function UsageHistoryItemFromJSON(json: any): UsageHistoryItem {
    return UsageHistoryItemFromJSONTyped(json, false);
}

export function UsageHistoryItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageHistoryItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'action': json['action'],
        'creditsUsed': json['creditsUsed'],
        'createdAt': (new Date(json['createdAt'])),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function UsageHistoryItemToJSON(json: any): UsageHistoryItem {
    return UsageHistoryItemToJSONTyped(json, false);
}

export function UsageHistoryItemToJSONTyped(value?: UsageHistoryItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'action': value['action'],
        'creditsUsed': value['creditsUsed'],
        'createdAt': value['createdAt'].toISOString(),
        'metadata': value['metadata'],
    };
}

