/* tslint:disable */
/* eslint-disable */
/**
 * RankVectors API
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentVerification } from './ContentVerification';
import {
    ContentVerificationFromJSON,
    ContentVerificationFromJSONTyped,
    ContentVerificationToJSON,
    ContentVerificationToJSONTyped,
} from './ContentVerification';

/**
 * 
 * @export
 * @interface VerifyContent200Response
 */
export interface VerifyContent200Response {
    /**
     * 
     * @type {boolean}
     * @memberof VerifyContent200Response
     */
    success?: boolean;
    /**
     * 
     * @type {ContentVerification}
     * @memberof VerifyContent200Response
     */
    verification?: ContentVerification;
}

/**
 * Check if a given object implements the VerifyContent200Response interface.
 */
export function instanceOfVerifyContent200Response(value: object): value is VerifyContent200Response {
    return true;
}

export function VerifyContent200ResponseFromJSON(json: any): VerifyContent200Response {
    return VerifyContent200ResponseFromJSONTyped(json, false);
}

export function VerifyContent200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyContent200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'verification': json['verification'] == null ? undefined : ContentVerificationFromJSON(json['verification']),
    };
}

export function VerifyContent200ResponseToJSON(json: any): VerifyContent200Response {
    return VerifyContent200ResponseToJSONTyped(json, false);
}

export function VerifyContent200ResponseToJSONTyped(value?: VerifyContent200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'verification': ContentVerificationToJSON(value['verification']),
    };
}

